### ISSUE TITLE
Starting usdview which was built on Fedora fails

### ISSUE THREAD

**Issue by flashingsquare** [PixarAnimationStudios/USD#1000]
### Description of Issue
Starting usdview which was build with the python script fails on my system with:

~~~~
Traceback (most recent call last):
  File "/home/knud/src/c++/phanes/thirdparty/USD/build/build_usdimaging/bin/usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
  File "/home/knud/src/c++/phanes/thirdparty/USD/build/build_usdimaging/lib/python/pxr/Usdviewq/__init__.py", line 28, in <module>
    from appController import AppController
  File "/home/knud/src/c++/phanes/thirdparty/USD/build/build_usdimaging/lib/python/pxr/Usdviewq/appController.py", line 34, in <module>
    from pxr import Usd, UsdGeom, UsdShade, UsdUtils, UsdImagingGL, Glf, Sdf, Tf, Ar
  File "/home/knud/src/c++/phanes/thirdparty/USD/build/build_usdimaging/lib/python/pxr/UsdImagingGL/__init__.py", line 24, in <module>
    from . import _usdImagingGL
ImportError: libPtex.so: cannot open shared object file: No such file or directory
~~~~

The Problem:
On my os some libraries are build into the folder lib and others (libPtex, libtiff, ...) are build into lib64.
lib64 is not added to the rpath in the cmake file.

Adding:
~~~~
_pxr_add_rpath(rpath "${CMAKE_INSTALL_PREFIX}/lib64")
~~~~
to cmake/macros/Private.cmake 

solved the issue for me.

### Steps to Reproduce
1. Build usdview on Fedora 29 
2. Try to launch it

### System Information (OS, Hardware)
Fedora 29

### Package Versions
v19.07

### Build Flags
python ../../build_scripts/build_usd.py --materialx --alembic --hdf5 --openimageio --usdview --usd-imaging --ptex /home/knud/src/c++/phanes/thirdparty/USD/build/build_usdimaging

**Comment by jilliene** [comment]
Filed as internal issue #USD-5632
