### ISSUE TITLE
Python fails to load USD modules

### ISSUE THREAD

**Issue by sorenvdb** [PixarAnimationStudios/USD#1087]
### Description of Issue

Python cannot import any of the USD packages including `pxr.Usd`,` pxr.Tf`, etc. Here is what happens when I try. This is the same error as closed issue #1033, but it's not fixed using any of the steps there.

```
Python 2.7.5 (default, Aug  7 2019, 00:51:29) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pxr.Usd
Warning: in Tf_PyLoadScriptModule at line 124 of ./source/USD/pxr/base/lib/tf/pyUtils.cpp -- Import failed for module 'pxr.Tf'!
Traceback (most recent call last):
  File "./install/USD/v19.11/lib/python/pxr/Tf/__init__.py", line 85, in <module>
    from . import _tf
AttributeError: 'NoneType' object has no attribute '__MFB_FULL_PACKAGE_NAME'
Warning: in Tf_PyLoadScriptModule at line 124 of ./source/USD/pxr/base/lib/tf/pyUtils.cpp -- Import failed for module 'pxr.Trace'!
Traceback (most recent call last):
  File "./install/USD/v19.11/lib/python/pxr/Trace/__init__.py", line 28, in <module>
    import _trace
AttributeError: 'NoneType' object has no attribute '__MFB_FULL_PACKAGE_NAME'
Warning: in Tf_PyLoadScriptModule at line 124 of ./source/USD/pxr/base/lib/tf/pyUtils.cpp -- Import failed for module 'pxr.Work'!
Traceback (most recent call last):
  File "./install/USD/v19.11/lib/python/pxr/Work/__init__.py", line 31, in <module>
    import _work
AttributeError: 'NoneType' object has no attribute '__MFB_FULL_PACKAGE_NAME'
Warning: in Tf_PyLoadScriptModule at line 124 of ./source/USD/pxr/base/lib/tf/pyUtils.cpp -- Import failed for module 'pxr.Plug'!
Traceback (most recent call last):
  File "./install/USD/v19.11/lib/python/pxr/Plug/__init__.py", line 28, in <module>
    import _plug
AttributeError: 'NoneType' object has no attribute '__MFB_FULL_PACKAGE_NAME'
Warning: in Tf_PyLoadScriptModule at line 124 of ./source/USD/pxr/base/lib/tf/pyUtils.cpp -- Import failed for module 'pxr.Gf'!
Traceback (most recent call last):
  File "./install/USD/v19.11/lib/python/pxr/Gf/__init__.py", line 31, in <module>
    from pxr import Tf
  File "./install/USD/v19.11/lib/python/pxr/Tf/__init__.py", line 98, in <module>
    __SetErrorExceptionClass(ErrorException)
NameError: name '__SetErrorExceptionClass' is not defined
Warning: in Tf_PyLoadScriptModule at line 124 of ./source/USD/pxr/base/lib/tf/pyUtils.cpp -- Import failed for module 'pxr.Vt'!
Traceback (most recent call last):
  File "./install/USD/v19.11/lib/python/pxr/Vt/__init__.py", line 31, in <module>
    import _vt
AttributeError: 'NoneType' object has no attribute '__MFB_FULL_PACKAGE_NAME'
Warning: in Tf_PyLoadScriptModule at line 124 of ./source/USD/pxr/base/lib/tf/pyUtils.cpp -- Import failed for module 'pxr.Ar'!
Traceback (most recent call last):
  File "./install/USD/v19.11/lib/python/pxr/Ar/__init__.py", line 24, in <module>
    import _ar
AttributeError: 'NoneType' object has no attribute '__MFB_FULL_PACKAGE_NAME'
Warning: in Tf_PyLoadScriptModule at line 124 of ./source/USD/pxr/base/lib/tf/pyUtils.cpp -- Import failed for module 'pxr.Kind'!
Traceback (most recent call last):
  File "./install/USD/v19.11/lib/python/pxr/Kind/__init__.py", line 26, in <module>
    from . import _kind
AttributeError: 'NoneType' object has no attribute '__MFB_FULL_PACKAGE_NAME'
Warning: in Tf_PyLoadScriptModule at line 124 of ./source/USD/pxr/base/lib/tf/pyUtils.cpp -- Import failed for module 'pxr.Sdf'!
Traceback (most recent call last):
  File "./install/USD/v19.11/lib/python/pxr/Sdf/__init__.py", line 24, in <module>
    import _sdf
AttributeError: 'NoneType' object has no attribute '__MFB_FULL_PACKAGE_NAME'
Warning: in Tf_PyLoadScriptModule at line 124 of ./source/USD/pxr/base/lib/tf/pyUtils.cpp -- Import failed for module 'pxr.Pcp'!
Traceback (most recent call last):
  File "./install/USD/v19.11/lib/python/pxr/Pcp/__init__.py", line 24, in <module>
    import _pcp
AttributeError: 'NoneType' object has no attribute '__MFB_FULL_PACKAGE_NAME'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./install/USD/v19.11/lib/python/pxr/Usd/__init__.py", line 24, in <module>
    import _usd
AttributeError: 'NoneType' object has no attribute '__MFB_FULL_PACKAGE_NAME'
>>> quit()

```

### Steps to Reproduce
1. Download and build glew, opensubdiv, ptex, and tbb from source, install to custom directories.
2. Install other dependencies using yum.
3. Configure and build USD using cmake, install to a custom directory.
4. Set PYTHONPATH and LD_LIBRARY_PATH to include ./install/USD/lib/python and ./install/USD/lib respectively. 
5. Open a python2.7 interpreter
7. Type `import pxr.Usd`

### System Information (OS, Hardware)

- centos7
- devtoolset-6 for compilers

### Package Versions
- v19.11
- v19.07
- dev branch on Jan 15 2020
### Build Flags
BOOST_USE_STATIC_LIBS=true
OpenGL_GL_PREFERENCE=GLVND
PYSIDE_USE_PYSIDE2 = TRUE
CMAKE_C_FLAGS and CMAKE_CXX_FLAGS = -fPIC
Others setting the locations of all of the libraries built from source
PYTHON_EXECUTABLE=/usr/bin/python2.7
PYTHON_INCLUDE_DIR=/usr/include/python2.7
PYTHON_LIBRARY = /usr/lib64/libpython2.7.so

**Comment by sorenvdb** [comment]
Using dynamic boost libraries gets rid of this error, but there's a similar error running usdview:

```
** (python2.7:16817): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "./install/USD/v19.11/bin/usdview", line 32, in <module>
    Usdviewq.Launcher().Run()
  File "./install/USD/v19.11/lib/python/pxr/Usdviewq/__init__.py", line 67, in Run
    self.__LaunchProcess(arg_parse_result)
  File "./install/USD/v19.11/lib/python/pxr/Usdviewq/__init__.py", line 290, in __LaunchProcess
    (app, appController) = self.LaunchPreamble(arg_parse_result)
  File "./install/USD/v19.11/lib/python/pxr/Usdviewq/__init__.py", line 280, in LaunchPreamble
    appController = AppController(arg_parse_result, contextCreator)
  File "./install/USD/v19.11/lib/python/pxr/Usdviewq/appController.py", line 358, in __init__
    self._ui.setupUi(self._mainWindow)
  File "./install/USD/v19.11/lib/python/pxr/Usdviewq/mainWindowUI.py", line 1032, in setupUi
    self.retranslateUi(MainWindow)
  File "./install/USD/v19.11/lib/python/pxr/Usdviewq/mainWindowUI.py", line 1081, in retranslateUi
    self.metadataView.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "Field Name", None, -1))
AttributeError: 'NoneType' object has no attribute 'setText'``
```

**Comment by jilliene** [comment]
Filed as internal issue #USD-5799

**Comment by sunyab** [comment]
@sorenvdb Glad you were able to figure out the original Python issue. For the record, USD does not support linking against static boost::python since that will create separate copies of various data structures (e.g. conversion registries) in each of the .so's.

Closing this out.

**Comment by Tadinu** [comment]
Hi @sorenvdb @sunyab, I got the same issue after installing `USD` by the default building script:
`python USD/build_scripts/build_usd.py /usr/local/USD`
Do you happen to know how to fix it?

This is my installing output log:
```
Building                      Shared libraries 
    Config                      Release 
    Imaging                     On 
      Ptex support:             Off 
      OpenVDB support:          Off 
      OpenImageIO support:      Off 
      OpenColorIO support:      Off 
      PRMan support:            Off 
    UsdImaging                  On 
      usdview:                  On 
    Python support              On 
      Python 3:                 On 
    Documentation               Off 
    Tests                       Off 
    Examples                    On 
    Tutorials                   On 
    Tools                       On 
    Alembic Plugin              Off 
      HDF5 support:             Off 
    Draco Plugin                Off 
    MaterialX Plugin            Off 
```
