### ISSUE TITLE
[usdview] Single UsdPrim -> Multiple Rprims Selection results in python exception

### ISSUE THREAD

**Issue by moddyz** [PixarAnimationStudios/USD#1091]
### Description of Issue

A custom prim adapter can insert **multiple** Rprims for a **single** UsdPrim.  This means that the render index path of the Rprim(s), with the potential exception of potentially one of them, must differ from the UsdPrim's prim path.

Opening the above scenario in `usdview`, if the user makes a selection on an Rprim whose render index path *does not* match the UsdPrim's prim path, the following exception is raised:
```python
Traceback (most recent call last):
 File "/vol/apps/usd/19.11/VP18/lib/python/pxr/Usdviewq/appController.py", line 4469, in onPrimSelected
   prim.GetPath(), instance)
 File "/vol/apps/usd/19.11/VP18/lib/python/pxr/Usdviewq/selectionDataModel.py", line 657, in switchToPrimPath
   path = self._ensureValidPrimPath(path)
 File "/vol/apps/usd/19.11/VP18/lib/python/pxr/Usdviewq/selectionDataModel.py", line 420, in _ensureValidPrimPath
   repr(sdfPath)))
ValueError: Path must be a prim path, got: Sdf.Path.emptyPath
```

The code at these locations suggest that `usdview` makes assumptions that the render index path of an Rprim must equal its associated UsdPrim path:
https://github.com/PixarAnimationStudios/USD/blob/v20.02-rc1/pxr/usdImaging/usdviewq/appController.py#L4451
https://github.com/PixarAnimationStudios/USD/blob/v20.02-rc1/pxr/usdImaging/usdImaging/delegate.cpp#L2138

### Steps to Reproduce
1. Introduce a new prim type.  In our example, we defined a custom `Triangle` prim which inherits from `Gprim`.
2. Introduce a new prim adapter which inherits from `UsdImagingGprimAdapter` which provides imaging for the `Triangle` prim.  In `Populate`, insert two or more Rprims, with different cache paths, and offset the different Rprim(s) in space (ie. providing different points for different cache paths) so they can be selected individually.
3. Author a new layer:
```
#usda 1.0                                                                                                                                                                

def Triangle "myTriangle" 
{
}
```
4. Launch the above layer in `usdview`, and select one of the Rprims whose render index path does not match its UsdPrim path.

### System Information (OS, Hardware)
Ubuntu-18.04

### Package Versions
usd-19.11

### Build Flags
Dynamic build

**Comment by jilliene** [comment]
Filed as internal issue #USD-5805
