### ISSUE TITLE
Error Usdview Main Window

### ISSUE THREAD

**Issue by dtempcyer** [PixarAnimationStudios/USD#1225]
### Description of Issue
When I try to run a test example of a **usd** file through **usdview**, it crashes with an interface error of the main viewer window.

Traceback (most recent call last):
  File "/home/alex/lib/usd/20.05/bin/usdview", line 32, in <module>
    Usdviewq.Launcher().Run()
  File "/home/alex/lib/usd/20.05/lib/python/pxr/Usdviewq/__init__.py", line 79, in Run
    self.__LaunchProcess(arg_parse_result)
  File "/home/alex/lib/usd/20.05/lib/python/pxr/Usdviewq/__init__.py", line 303, in __LaunchProcess
    (app, appController) = self.LaunchPreamble(arg_parse_result)
  File "/home/alex/lib/usd/20.05/lib/python/pxr/Usdviewq/__init__.py", line 293, in LaunchPreamble
    appController = AppController(arg_parse_result, contextCreator)
  File "/home/alex/lib/usd/20.05/lib/python/pxr/Usdviewq/appController.py", line 427, in __init__
    self._ui.setupUi(self._mainWindow)
  File "/home/alex/lib/usd/20.05/lib/python/pxr/Usdviewq/mainWindowUI.py", line 1146, in setupUi
    self.retranslateUi(MainWindow)
  File "/home/alex/lib/usd/20.05/lib/python/pxr/Usdviewq/mainWindowUI.py", line 1204, in retranslateUi
    self.metadataView.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "Field Name", None, -1))
AttributeError: 'NoneType' object has no attribute 'setText'

### Steps to Reproduce
1. Set variables 
export PYTHONPATH=${PYTHONPATH}:$HOME/lib/usd/20.05/lib/python
export PATH=${PATH}:$HOME/lib/usd/20.05/bin

2. usdview lib/usd/examples/teapot/teapot.usdc // any usd file

### System Information (OS, Hardware)
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.12 (stretch)
Release:	        9.12
Codename:	stretch

### Package Versions
USD 20.05
Python 2.7
PySide2 5.13.0

### Build Flags
python build_usd.py /home/alex/lib/usd/20.05 -v -j 4 --tests --docs --imaging --openvdb --prman --prman-location /opt/pixar/RenderManProServer-23.2 --openimageio --opencolorio --alembic --hdf5 --materialx

**Comment by sunyab** [comment]
Hi @alexwheezy, this is an issue in PySide2 5.13, please see #914 for more details. Thanks!

**Comment by jtran56** [comment]
Filed as internal issue #USD-6092.
