### ISSUE TITLE
usdview not draw meshes

### ISSUE THREAD

**Issue by tufeixp** [PixarAnimationStudios/USD#1231]
On my windows 10 pc, the usdview works without drawing meshes normally(occasionally draw some mesh and can only draw skeletons), printing:

  File "D:\Github\build\usd-win64-dev\usd-win64\lib\python\pxr\Usdviewq\stageView.py", line 89, in __init__
    self.program   = GL.glCreateProgram()
WindowsError: exception: access violation reading 0x0000000000000010
Traceback (most recent call last):
  File "D:\Github\build\usd-win64-dev\usd-win64\lib\python\pxr\Usdviewq\stageView.py", line 1754, in paintGL
    self.DrawAxis(viewProjectionMatrix)
  File "D:\Github\build\usd-win64-dev\usd-win64\lib\python\pxr\Usdviewq\stageView.py", line 1081, in DrawAxis
    glslProgram = self.GetSimpleGLSLProgram()
  File "D:\Github\build\usd-win64-dev\usd-win64\lib\python\pxr\Usdviewq\stageView.py", line 1073, in GetSimpleGLSLProgram
    ["mvpMatrix", "color"])
---------------------------------
PyOpenGL Version: 3.1.5

**Comment by jtran56** [comment]
Filed as internal issue #USD-6101.
