### ISSUE TITLE
'GlfContextCaps has not been initialized' when trying to start usdview

### ISSUE THREAD

**Issue by mhamid3d** [PixarAnimationStudios/USD#1355]
### Description of Issue
I have just built USD and tried opening some example scenes. When I start usdview with `usdview /path/to/scene.usd` , the window appears for a split second before closing and the log says as follows:
```
Warning: in _ReportErrors at line 2815 of /home/mhamid/Downloads/USD/pxr/usd/usd/stage.cpp -- Could not open asset @/opt/usd/20.08/share/usd/examples/plugin/usdDancingCubesExample/resources/usdDancingCubesExample/empty.usddancingcubesexample@ for payload on prim @dancingCubes.usda@,@anon:0x5565c2696640@</Root> -- Cannot determine file format for @/opt/usd/20.08/share/usd/examples/plugin/usdDancingCubesExample/resources/usdDancingCubesExample/empty.usddancingcubesexample:SDF_FORMAT_ARGS:target=usd@. (instantiating stage on stage @dancingCubes.usda@ <0x5565c1d96540>)
Traceback (most recent call last):
  File "/opt/usd/20.08/lib/python/pxr/Usdviewq/stageView.py", line 2310, in _primSelectionChanged
    self.updateSelection()
  File "/opt/usd/20.08/lib/python/pxr/Usdviewq/stageView.py", line 1318, in updateSelection
    renderer = self._getRenderer()
  File "/opt/usd/20.08/lib/python/pxr/Usdviewq/stageView.py", line 934, in _getRenderer
    raise RuntimeError("StageView could not initialize renderer without a valid GL context")
RuntimeError: StageView could not initialize renderer without a valid GL context
Traceback (most recent call last):
  File "/opt/usd/20.08/bin/usdview", line 32, in <module>
    Usdviewq.Launcher().Run()
  File "/opt/usd/20.08/lib/python/pxr/Usdviewq/__init__.py", line 79, in Run
    self.__LaunchProcess(arg_parse_result)
  File "/opt/usd/20.08/lib/python/pxr/Usdviewq/__init__.py", line 324, in __LaunchProcess
    (app, appController) = self.LaunchPreamble(arg_parse_result)
  File "/opt/usd/20.08/lib/python/pxr/Usdviewq/__init__.py", line 314, in LaunchPreamble
    appController = AppController(arg_parse_result, contextCreator)
  File "/opt/usd/20.08/lib/python/pxr/Usdviewq/appController.py", line 1127, in __init__
    self._drawFirstImage()
  File "/opt/usd/20.08/lib/python/pxr/Usdviewq/appController.py", line 1143, in _drawFirstImage
    self._configureColorManagement()
  File "/opt/usd/20.08/lib/python/pxr/Usdviewq/appController.py", line 1640, in _configureColorManagement
    UsdImagingGL.Engine.IsColorCorrectionCapable())
pxr.Tf.ErrorException: 
	Error in 'pxrInternal_v0_20__pxrReserved__::GlfContextCaps::GetInstance' at line 120 in file /home/mhamid/Downloads/USD/pxr/imaging/glf/contextCaps.cpp : 'GlfContextCaps has not been initialized'
```

Also I'm wondering why in the last line it says `in file /home/mhamid/Downloads/USD/pxr/imaging/glf/contextCaps.cpp` . This is the location where I built USD from source, so I'm not sure why there are still references to this location in the libraries.

To build USD I used the build_usd.py and a manual CMAKE install, both providing the same errors

USD Release Tag: 20.08
Ubuntu 20.04

ENVS:
PYTHONPATH=/opt/usd/20.08/lib/python
PATH=/opt/usd/20.08/bin

**Comment by mhamid3d** [comment]
The issue was resolved after rebooting the system.
