### ISSUE TITLE
[usdview] OpenGL context required, using reference renderer [windows10]

### ISSUE THREAD

**Issue by stephanebertrand** [PixarAnimationStudios/USD#1467]
### Description of Issue
Similar to issu https://github.com/PixarAnimationStudios/USD/issues/764 with black windows for viewport.

```
 Traceback (most recent call last):
  File "e:\build_usd\lib\python\pxr\Usdviewq\stageView.py", line 1660, in paintGL
    renderer = self._getRenderer()
  File "e:\build_usd\lib\python\pxr\Usdviewq\stageView.py", line 971, in _getRenderer
    self._renderer = UsdImagingGL.Engine()
pxr.Tf.ErrorException:
        Error in 'pxrInternal_v0_21__pxrReserved__::GlfContextCaps::_LoadCaps' at line 162 in file E:\USD\pxr\imaging\glf\contextCaps.cpp : 'Failed verification: ' GlfGLContext::GetCurrentGLContext()->IsValid() ''
        Error in 'pxrInternal_v0_21__pxrReserved__::`anonymous-namespace'::_IsHydraEnabled' at line 109 in file E:\USD\pxr\usdImaging\usdImagingGL\engine.cpp : 'OpenGL context required, using reference renderer'
ERROR: Usdview encountered an error while rendering.GLError(
        err = 1282,
        description = b'op\xe9ration non valide',
        baseOperation = glClearColor,
        cArguments = (0.0, 0.0, 0.0, 0.0)
)
```

usdview launch write 
### Steps to Reproduce
1. usdview ./USD/extras/usd/tutorials/convertingLayerFormats/Sphere.usda

### System Information (OS, Hardware)
Windows 10
Geforce GTX 1060

### Package Versions
Python 3.7
PySide2 5.15.2

### Build Flags
python.exe build_usd.py ./build_usd -j 4 --examples --tutorials --tools --python --usd-imaging --usdview --embree --no-prman --openimageio --opencolorio --alembic --material --openvdb --hdf5 --tests

**Comment by jilliene** [comment]
Filed as internal issue #USD-6590

**Comment by meshula** [comment]
Is it possible to test with

Pyside 6
Pyside2 5.14.1

As you can see here, PySide2 5.15.x is not part of the test matrix, as it tends to have issues such as you are encountering.
