### ISSUE TITLE
Crash with TF_DEBUG="PCP*" with Classes, Variants and Payloads

### ISSUE THREAD

**Issue by aloysbaillet** [PixarAnimationStudios/USD#157]
### Description of Issue

Hi,

When turning on TF_DEBUG="PCP*" on a stage that contains both Classes, Variants and Payloads we get a crash. This was reported initially there: https://groups.google.com/forum/#!topic/usd-interest/XhIKmjrZsL4 and could be related to #156 as the repro steps are identical.

Cheers,

Aloys

### Steps to Reproduce

1. Create these two usd files bob.usd and bob_geo.usd:

bob.usd
```
#usda 1.0

class "_class_geotype" (
    add variantSets = ["geotype_selector", "geotype"]
)
{
    variantSet "geotype_selector" = {
        "select_cube" (
              variants = {
                  string geotype = "cube"
              }
        ){
        }
        "select_sphere" (
              variants = {
                  string geotype = "sphere"
              }
        ){
        }
    }
}

def "bob"(
  add inherits = [</_class_geotype>]
  add variantSets = ["geotype"]
){
  variantSet "geotype" = {
    "sphere" (
        payload = @bob_geo.usd@</bob_root_sphere>
    )
    {
    }
    "cube" (
        payload = @bob_geo.usd@</bob_root_cube>
    )
    {
    }
  }
}
```

bob_geo.usd
```
#usda 1.0
(
)

def Xform "bob_root_sphere"(
){
  def Sphere "bob_body"(
  ){
  }
}

def Xform "bob_root_cube"(
){
  def Cube "bob_body"(
  ){
  }
}
```

2. Run this:
`TF_DEBUG="PCP*" usdview bob.usd`
will crash with this stacktrace:
```
Program received signal SIGSEGV, Segmentation fault.
Pcp_GraphOutputManager::_FlushGraphIfNeedsOutput (this=0x25656f0) at usdBase/pxr/usd/lib/pcp/diagnostic.cpp:670
670 usdBase/pxr/usd/lib/pcp/diagnostic.cpp: No such file or directory.
(gdb) bt
#0 Pcp_GraphOutputManager::_FlushGraphIfNeedsOutput (this=0x25656f0) at usdBase/pxr/usd/lib/pcp/diagnostic.cpp:670
#1 0x00007fffc3b54944 in Pcp_GraphOutputManager::Update (this=0x25656f0, msg="Added new node for site @bob.usd@,@anon:0x2563540:bob-session.usda@</_class_geotype> to graph", 
 updatedNode=...) at usdBase/pxr/usd/lib/pcp/diagnostic.cpp:773
#2 0x00007fffc3b54c31 in Pcp_GraphUpdate (node=..., format=format@entry=0x7fffc3bc5810 "Added new node for site %s to graph")
 at usdBase/pxr/usd/lib/pcp/diagnostic.cpp:855
#3 0x00007fffc3b8dec8 in _AddArc (arcType=arcType@entry=PcpArcTypeGlobalInherit, parent=..., origin=..., site=..., mapExpr=..., arcSiblingNum=arcSiblingNum@entry=0, namespaceDepth=1, 
 directNodeShouldContributeSpecs=directNodeShouldContributeSpecs@entry=true, includeAncestralOpinions=includeAncestralOpinions@entry=false, 
 requirePrimAtTarget=requirePrimAtTarget@entry=true, skipDuplicateNodes=skipDuplicateNodes@entry=true, skipImpliedSpecializes=skipImpliedSpecializes@entry=false, 
 indexer=indexer@entry=0x7fffffff1390) at usdBase/pxr/usd/lib/pcp/primIndex.cpp:1311
#4 0x00007fffc3b8ebdb in _AddArc (arcType=arcType@entry=PcpArcTypeGlobalInherit, parent=..., origin=..., site=..., mapExpr=..., arcSiblingNum=arcSiblingNum@entry=0, 
 directNodeShouldContributeSpecs=directNodeShouldContributeSpecs@entry=true, includeAncestralOpinions=includeAncestralOpinions@entry=false, 
 requirePrimAtTarget=requirePrimAtTarget@entry=true, skipDuplicateNodes=skipDuplicateNodes@entry=true, indexer=indexer@entry=0x7fffffff1390)
 at usdBase/pxr/usd/lib/pcp/primIndex.cpp:1515
#5 0x00007fffc3b92efa in _AddClassBasedArc (arcType=arcType@entry=PcpArcTypeGlobalInherit, parent=..., origin=..., inheritMap=..., inheritArcNum=inheritArcNum@entry=0, 
 ignoreIfSameAsSite=..., requirePrimAtTarget=requirePrimAtTarget@entry=true, indexer=indexer@entry=0x7fffffff1390)
 at usdBase/pxr/usd/lib/pcp/primIndex.cpp:2167
#6 0x00007fffc3b933d9 in _AddClassBasedArcs (node=..., classArcs=std::vector of length 1, capacity 1 = {...}, globalArcType=globalArcType@entry=PcpArcTypeGlobalInherit, 
 localArcType=localArcType@entry=PcpArcTypeLocalInherit, indexer=indexer@entry=0x7fffffff1390, index=0x7fffebdabe88)
 at usdBase/pxr/usd/lib/pcp/primIndex.cpp:2206
#7 0x00007fffc3b95813 in _EvalNodeInherits (index=0x7fffebdabe88, indexer=0x7fffffff1390, node=...) at usdBase/pxr/usd/lib/pcp/primIndex.cpp:2524
#8 Pcp_BuildPrimIndex (site=..., rootSite=..., evaluateImpliedSpecializes=evaluateImpliedSpecializes@entry=true, evaluateVariants=evaluateVariants@entry=true, 
 directNodeShouldContributeSpecs=directNodeShouldContributeSpecs@entry=true, previousFrame=previousFrame@entry=0x0, inputs=..., outputs=outputs@entry=0x7fffebdabe88)
 at usdBase/pxr/usd/lib/pcp/primIndex.cpp:4013
#9 0x00007fffc3b9821b in PcpComputePrimIndex (primPath=..., layerStack=..., inputs=..., outputs=0x7fffebdabe88, resolver=0x1c7ed30)
 at usdBase/pxr/usd/lib/pcp/primIndex.cpp:4065
#10 0x00007fffc3b357f5 in Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>::_ComputeIndex (this=0x7fffffff1e70, parentIndex=0x7fffebdabd80, path=..., 
 checkCache=<optimized out>) at usdBase/pxr/usd/lib/pcp/cache.cpp:2574
#11 0x00007fffc3b2bf20 in std::_Mem_fn<void (Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>::*)(PcpPrimIndex const*, SdfPath, bool)>::operator()<const PcpPrimIndex*&, SdfPath&, bool&, void> (__object=<optimized out>, this=0x7fffebe3f548) at stdlib/4.8.3/CentOS-6.2_thru_7/include/c++/4.8.3/functional:601
#12 std::_Bind<std::_Mem_fn<void (Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>::*)(const PcpPrimIndex*, SdfPath, bool)>(Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>*, const PcpPrimIndex*, SdfPath, bool)>::__call<void, 0ul, 1ul, 2ul, 3ul> (__args=<optimized out>, this=0x7fffebe3f548)
 at stdlib/4.8.3/CentOS-6.2_thru_7/include/c++/4.8.3/functional:1296
#13 std::_Bind<std::_Mem_fn<void (Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>::*)(const PcpPrimIndex*, SdfPath, bool)>(Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>*, const PcpPrimIndex*, SdfPath, bool)>::operator()<, void> (this=0x7fffebe3f548) at stdlib/4.8.3/CentOS-6.2_thru_7/include/c++/4.8.3/functional:1355
#14 WorkDispatcher::_InvokerTask<std::_Bind<std::_Mem_fn<void (Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>::*)(PcpPrimIndex const*, SdfPath, bool)> (Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>*, PcpPrimIndex const*, SdfPath, bool)> >::execute() (this=0x7fffebe3f540)
 at usdBase/build/include/pxr/base/work/dispatcher.h:145
#15 0x00007fffec0b1973 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7fffebe28c00, parent=..., child=<optimized out>)
 at ../../src/tbb/custom_scheduler.h:463
#16 0x00007fffed065b54 in tbb::task::wait_for_all (this=<optimized out>) at tbb/4.4.2/CentOS-6.2_thru_7/include/tbb/task.h:747
#17 WorkDispatcher::Wait (this=this@entry=0x7fffffff1fb0) at usdBase/pxr/base/lib/work/dispatcher.cpp:49
#18 0x00007fffc3b34e2c in Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>::RunAndWait (this=this@entry=0x7fffffff1e70)
 at usdBase/pxr/usd/lib/pcp/cache.cpp:2529
#19 0x00007fffc3b266d4 in PcpCache::_ComputePrimIndexesInParallel (this=0x2561bf0, roots=std::vector of length 1, capacity 1 = {...}, allErrors=allErrors@entry=0x7fffffff21b0, 
 childrenPred=..., payloadPred=..., mallocTag1=mallocTag1@entry=0x7fffe03d0c4f "Usd", mallocTag2=0x7fffe03eb532 "UsdStages in aggregate")
 at usdBase/pxr/usd/lib/pcp/cache.cpp:2767
#20 0x00007fffe0379912 in PcpCache::ComputePrimIndexesInParallel<(anonymous namespace)::_NameChildrenPred, UsdStage::_ComposePrimIndexesInParallel(const std::vector<SdfPath>&, UsdStage::_IncludePayloadsRule, const string&, Usd_InstanceChanges*)::__lambda15> (mallocTag1=<optimized out>, mallocTag2=<optimized out>, payloadPred=..., childrenPred=..., 
 allErrors=<optimized out>, paths=..., this=<optimized out>) at usdBase/build/include/pxr/usd/pcp/cache.h:323
#21 UsdStage::_ComposePrimIndexesInParallel (this=0x2562ca0, primIndexPaths=std::vector of length 1, capacity 1 = {...}, 
 includeRule=includeRule@entry=UsdStage::_IncludeNoDiscoveredPayloads, context="Instantiating stage", instanceChanges=instanceChanges@entry=0x0)
 at usdBase/pxr/usd/lib/usd/stage.cpp:3322
#22 0x00007fffe0395470 in UsdStage::_InstantiateStage (rootLayer=..., sessionLayer=..., pathResolverContext=..., load=load@entry=UsdStage::LoadNone)
 at usdBase/pxr/usd/lib/usd/stage.cpp:528
#23 0x00007fffe0396b91 in UsdStage::Open (rootLayer=..., pathResolverContext=..., load=load@entry=UsdStage::LoadNone)
 at usdBase/pxr/usd/lib/usd/stage.cpp:814
#24 0x00007fffe0397265 in UsdStage::Open (filePath="bob.usd", pathResolverContext=..., load=UsdStage::LoadNone)
 at usdBase/pxr/usd/lib/usd/stage.cpp:716
#25 0x00007fffe0816446 in boost::python::detail::invoke<Tf_MakePyConstructor::_RefPtrFactoryConverter<TfWeakPtr<UsdStage>, TfRefPtr<UsdStage> >, TfRefPtr<UsdStage> (*)(std::basic_string<char> const&, ArResolverContext const&, UsdStage::InitialLoadSet), boost::python::arg_from_python<std::basic_string<char> const&>, boost::python::arg_from_python<ArResolverContext const&>, boost::python::arg_from_python<UsdStage::InitialLoadSet> > (ac2=..., ac1=..., ac0=..., f=<optimized out>, rc=...)
 at AL_boost/1.55.0/CentOS-6.2_thru_7/include/boost/python/detail/invoke.hpp:75
#26 boost::python::detail::caller_arity<3u>::impl<TfRefPtr<UsdStage> (*)(std::string const&, ArResolverContext const&, UsdStage::InitialLoadSet), boost::python::return_value_policy<TfPyRefPtrFactory<void>, boost::python::default_call_policies>, boost::mpl::vector4<TfRefPtr<UsdStage>, std::string const&, ArResolverContext const&, UsdStage::InitialLoadSet> >::operator() (args_=<optimized out>, this=<optimized out>) at AL_boost/1.55.0/CentOS-6.2_thru_7/include/boost/python/detail/caller.hpp:223
---Type <return> to continue, or q <return> to quit---
#27 boost::python::objects::caller_py_function_impl<boost::python::detail::caller<TfRefPtr<UsdStage> (*)(std::string const&, ArResolverContext const&, UsdStage::InitialLoadSet), boost::python::return_value_policy<TfPyRefPtrFactory<void>, boost::python::default_call_policies>, boost::mpl::vector4<TfRefPtr<UsdStage>, std::string const&, ArResolverContext const&, UsdStage::InitialLoadSet> > >::operator() (this=<optimized out>, args=<optimized out>, kw=<optimized out>)
 at AL_boost/1.55.0/CentOS-6.2_thru_7/include/boost/python/object/py_function.hpp:38
#28 0x00007fffecb3e071 in boost::python::objects::function::call(_object*, _object*) const () from /tmp/rez_context_jNSM66/LD_LIBRARY_PATH/libboost_python-mt.so.1.55.0
#29 0x00007fffecb3e508 in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) () from /tmp/rez_context_jNSM66/LD_LIBRARY_PATH/libboost_python-mt.so.1.55.0
#30 0x00007fffecb45e5b in boost::python::handle_exception_impl(boost::function0<void>) () from /tmp/rez_context_jNSM66/LD_LIBRARY_PATH/libboost_python-mt.so.1.55.0
#31 0x00007fffecb3aa28 in function_call () from /tmp/rez_context_jNSM66/LD_LIBRARY_PATH/libboost_python-mt.so.1.55.0
#32 0x0000003a544468a3 in PyObject_Call (func=<Boost.Python.function at remote 0x175c490>, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2529
#33 0x00007fffecdf7a7d in Tf_ModuleProcessor::_InvokeWithErrorHandling (fn=..., funcName=..., fileName=..., funcLine=<optimized out>, args=..., kw=...)
 at usdBase/pxr/base/lib/tf/pyModule.cpp:168
#34 0x00007fffecdf74df in boost::_bi::list6<boost::_bi::value<boost::python::api::object>, boost::_bi::value<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<int>, boost::arg<1>, boost::arg<2> >::operator()<boost::python::handle<>, boost::python::handle<> (*)(const boost::python::api::object&, const std::basic_string<char>&, const std::basic_string<char>&, int, const boost::python::tuple&, const boost::python::dict&), boost::_bi::list2<const boost::python::tuple&, const boost::python::dict&> > (f=
 @0x17c1c78: 0x7fffecdf7a10 <Tf_ModuleProcessor::_InvokeWithErrorHandling(boost::python::api::object const&, std::string const&, std::string const&, int, boost::python::tuple const&, boost::python::dict const&)>, a=<synthetic pointer>, this=0x17c1c80) at AL_boost/1.55.0/CentOS-6.2_thru_7/include/boost/bind/bind.hpp:586
#35 boost::_bi::bind_t<boost::python::handle<_object>, boost::python::handle<_object> (*)(boost::python::api::object const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, boost::python::tuple const&, boost::python::dict const&), boost::_bi::list6<boost::_bi::value<boost::python::api::object>, boost::_bi::value<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<int>, boost::arg<1>, boost::arg<2> > >::operator()<boost::python::tuple, boost::python::dict> (a2=..., 
 a1=..., this=0x17c1c78) at AL_boost/1.55.0/CentOS-6.2_thru_7/include/boost/bind/bind_template.hpp:102
#36 boost::python::detail::invoke<boost::python::to_python_value<const boost::python::handle<>&>, boost::_bi::bind_t<boost::python::handle<>, boost::python::handle<> (*)(const boost::python::api::object&, const std::basic_string<char>&, const std::basic_string<char>&, int, const boost::python::tuple&, const boost::python::dict&), boost::_bi::list6<boost::_bi::value<boost::python::api::object>, boost::_bi::value<std::basic_string<char> >, boost::_bi::value<std::basic_string<char> >, boost::_bi::value<int>, boost::arg<1>, boost::arg<2> > >, boost::python::arg_from_python<boost::python::tuple>, boost::python::arg_from_python<boost::python::dict> > (ac1=<synthetic pointer>, ac0=<synthetic pointer>, 
 f=..., rc=...) at AL_boost/1.55.0/CentOS-6.2_thru_7/include/boost/python/detail/invoke.hpp:75
#37 boost::python::detail::caller_arity<2u>::impl<boost::_bi::bind_t<boost::python::handle<_object>, boost::python::handle<_object> (*)(boost::python::api::object const&, std::string const&, std::string const&, int, boost::python::tuple const&, boost::python::dict const&), boost::_bi::list6<boost::_bi::value<boost::python::api::object>, boost::_bi::value<std::string>, boost::_bi::value<std::string>, boost::_bi::value<int>, boost::arg<1>, boost::arg<2> > >, boost::python::default_call_policies, boost::mpl::vector<boost::python::handle<_object>, boost::python::tuple, boost::python::dict, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na> >::operator() (args_=<optimized out>, this=0x17c1c78)
 at AL_boost/1.55.0/CentOS-6.2_thru_7/include/boost/python/detail/caller.hpp:223
#38 boost::python::objects::caller_py_function_impl<boost::python::detail::caller<boost::_bi::bind_t<boost::python::handle<_object>, boost::python::handle<_object> (*)(boost::python::api::object const&, std::string const&, std::string const&, int, boost::python::tuple const&, boost::python::dict const&), boost::_bi::list6<boost::_bi::value<boost::python::api::object>, boost::_bi::value<std::string>, boost::_bi::value<std::string>, boost::_bi::value<int>, boost::arg<1>, boost::arg<2> > >, boost::python::default_call_policies, boost::mpl::vector<boost::python::handle<_object>, boost::python::tuple, boost::python::dict, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na> > >::operator() (this=0x17c1c70, args=<optimized out>, kw=<optimized out>)
 at AL_boost/1.55.0/CentOS-6.2_thru_7/include/boost/python/object/py_function.hpp:38
#39 0x00007fffecb3e071 in boost::python::objects::function::call(_object*, _object*) const () from /tmp/rez_context_jNSM66/LD_LIBRARY_PATH/libboost_python-mt.so.1.55.0
#40 0x00007fffecb3e508 in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) () from /tmp/rez_context_jNSM66/LD_LIBRARY_PATH/libboost_python-mt.so.1.55.0
#41 0x00007fffecb45e5b in boost::python::handle_exception_impl(boost::function0<void>) () from /tmp/rez_context_jNSM66/LD_LIBRARY_PATH/libboost_python-mt.so.1.55.0
#42 0x00007fffecb3aa28 in function_call () from /tmp/rez_context_jNSM66/LD_LIBRARY_PATH/libboost_python-mt.so.1.55.0
#43 0x0000003a544468a3 in PyObject_Call (func=<Boost.Python.function at remote 0x17c1cb0>, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2529
#44 0x0000003a544e3a93 in PyEval_CallObjectWithKeywords (func=<Boost.Python.function at remote 0x17c1cb0>, arg=
 (('bob.usd', <ResolverContext at remote 0x1d2b280>, <InitialLoadSet(__module__='pxr.Usd') at remote 0x15cd950>), {}), kw=<optimized out>) at Python/ceval.c:3890
#45 0x0000003a5450398a in PyEval_CallFunction (obj=<Boost.Python.function at remote 0x17c1cb0>, format=<optimized out>) at Python/modsupport.c:557
#46 0x00007fffecdf7369 in boost::python::call<boost::python::api::object, boost::python::tuple, boost::python::dict> (a1=..., a0=..., callable=<optimized out>)
 at AL_boost/1.55.0/CentOS-6.2_thru_7/include/boost/python/call.hpp:66
#47 boost::python::api::object_operators<boost::python::api::object>::operator()<boost::python::tuple, boost::python::dict> (a1=..., a0=..., this=0x17c1be8)
 at AL_boost/1.55.0/CentOS-6.2_thru_7/include/boost/python/object_call.hpp:19
#48 boost::python::detail::raw_dispatcher<boost::python::api::object>::operator() (keywords=<optimized out>, 
 args=('bob.usd', <ResolverContext at remote 0x1d2b280>, <InitialLoadSet(__module__='pxr.Usd') at remote 0x15cd950>), this=0x17c1be8)
 at AL_boost/1.55.0/CentOS-6.2_thru_7/include/boost/python/raw_function.hpp:36
#49 boost::python::objects::full_py_function_impl<boost::python::detail::raw_dispatcher<boost::python::api::object>, boost::mpl::vector1<_object*> >::operator() (this=0x17c1be0, 
 args=('bob.usd', <ResolverContext at remote 0x1d2b280>, <InitialLoadSet(__module__='pxr.Usd') at remote 0x15cd950>), kw=<optimized out>)
 at AL_boost/1.55.0/CentOS-6.2_thru_7/include/boost/python/object/py_function.hpp:94
#50 0x00007fffecb3e071 in boost::python::objects::function::call(_object*, _object*) const () from /tmp/rez_context_jNSM66/LD_LIBRARY_PATH/libboost_python-mt.so.1.55.0
#51 0x00007fffecb3e508 in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) () from /tmp/rez_context_jNSM66/LD_LIBRARY_PATH/libboost_python-mt.so.1.55.0
#52 0x00007fffecb45e5b in boost::python::handle_exception_impl(boost::function0<void>) () from /tmp/rez_context_jNSM66/LD_LIBRARY_PATH/libboost_python-mt.so.1.55.0
#53 0x00007fffecb3aa28 in function_call () from /tmp/rez_context_jNSM66/LD_LIBRARY_PATH/libboost_python-mt.so.1.55.0
#54 0x0000003a544468a3 in PyObject_Call (func=<Boost.Python.function at remote 0x17c1d00>, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2529
---Type <return> to continue, or q <return> to quit---
#55 0x0000003a544e964e in do_call (nk=<optimized out>, na=<optimized out>, pp_stack=0x7fffffff2f78, func=<Boost.Python.function at remote 0x17c1d00>) at Python/ceval.c:4239
#56 call_function (oparg=<optimized out>, pp_stack=0x7fffffff2f78) at Python/ceval.c:4044
#57 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2666
#58 0x0000003a544ea7dd in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fffffff30c8, func=<function at remote 0x1ccc938>) at Python/ceval.c:4107
#59 call_function (oparg=<optimized out>, pp_stack=0x7fffffff30c8) at Python/ceval.c:4042
#60 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2666
#61 0x0000003a544ebdbe in PyEval_EvalCodeEx (co=0x1010530, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=3, kws=0x0, kwcount=0, defs=0x0, defcount=0, 
 closure=0x0) at Python/ceval.c:3253
#62 0x0000003a54472471 in function_call (func=<function at remote 0x1ccc6e0>, arg=
 (<MainWindow(_currentNodes=[], _unloaded=False, _printTiming=False, _updateBlock=0, _nodeViewHelpDlg=None, _mallocTags='none', _debug=False, _deprecatedStatusFileName='.usdviewrc', _pathResolverContext=<ResolverContext at remote 0x1d2b280>, _interpreter=None, _console=None, _ui=<Ui_MainWindow(actionFrame_Backwards=<PySide.QtGui.QAction at remote 0x1cd87e8>, actionComplexity=<PySide.QtGui.QAction at remote 0x1cd8ef0>, actionHUD_VBOInfo=<PySide.QtGui.QAction at remote 0x1cda368>, attributeInspectorFrame=<PySide.QtGui.QFrame at remote 0x1cd29e0>, actionReset_View=<PySide.QtGui.QAction at remote 0x1cd8680>, nodeFindContainer=<PySide.QtGui.QHBoxLayout at remote 0x1ccfcf8>, actionHD_Flags=<PySide.QtGui.QAction at remote 0x1cdab90>, actionShow_Master_Prims=<PySide.QtGui.QAction at remote 0x1cdad40>, topBottomSplitter=<PySide.QtGui.QSplitter at remote 0x1ccfab8>, actionVersion_Info=<PySide.QtGui.QAction at remote 0x1cda7e8>, menubar=<PySide.QtGui.QMenuBar at remote 0x1cd6fc8>, actionPick_Models=<PySide.QtGui.QAction ...(truncated), kw=0x0) at Objects/funcobject.c:526
#63 0x0000003a544468a3 in PyObject_Call (func=<function at remote 0x1ccc6e0>, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2529
#64 0x0000003a5445bfff in instancemethod_call (func=<function at remote 0x1ccc6e0>, 
 arg=(<MainWindow(_currentNodes=[], _unloaded=False, _printTiming=False, _updateBlock=0, _nodeViewHelpDlg=None, _mallocTags='none', _debug=False, _deprecatedStatusFileName='.usdviewrc', _pathResolverContext=<ResolverContext at remote 0x1d2b280>, _interpreter=None, _console=None, _ui=<Ui_MainWindow(actionFrame_Backwards=<PySide.QtGui.QAction at remote 0x1cd87e8>, actionComplexity=<PySide.QtGui.QAction at remote 0x1cd8ef0>, actionHUD_VBOInfo=<PySide.QtGui.QAction at remote 0x1cda368>, attributeInspectorFrame=<PySide.QtGui.QFrame at remote 0x1cd29e0>, actionReset_View=<PySide.QtGui.QAction at remote 0x1cd8680>, nodeFindContainer=<PySide.QtGui.QHBoxLayout at remote 0x1ccfcf8>, actionHD_Flags=<PySide.QtGui.QAction at remote 0x1cdab90>, actionShow_Master_Prims=<PySide.QtGui.QAction at remote 0x1cdad40>, topBottomSplitter=<PySide.QtGui.QSplitter at remote 0x1ccfab8>, actionVersion_Info=<PySide.QtGui.QAction at remote 0x1cda7e8>, menubar=<PySide.QtGui.QMenuBar at remote 0x1cd6fc8>, actionPick_Models=<PySide.QtGui.QAction ...(truncated), kw=0x0) at Objects/classobject.c:2578
#65 0x0000003a544468a3 in PyObject_Call (func=<instancemethod at remote 0x7ffff7eaca50>, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2529
#66 0x0000003a544a405e in slot_tp_init (self=<optimized out>, 
 args=(None, <Namespace(lastframe=None, numThreads=0, mallocTagStats='none', quitAfterStartup=False, complexity=<float at remote 0x622570>, renderer='opt', primPath='/', timing=False, noRender=False, firstframe=None, clearSettings=False, unloaded=False, usdFile='bob.usd') at remote 0x101ad50>), kwds=0x0) at Objects/typeobject.c:5663
#67 0x0000003a544a2b48 in type_call (type=<optimized out>, 
 args=(None, <Namespace(lastframe=None, numThreads=0, mallocTagStats='none', quitAfterStartup=False, complexity=<float at remote 0x622570>, renderer='opt', primPath='/', timing=False, noRender=False, firstframe=None, clearSettings=False, unloaded=False, usdFile='bob.usd') at remote 0x101ad50>), kwds=0x0) at Objects/typeobject.c:737
#68 0x0000003a544468a3 in PyObject_Call (func=<Shiboken.ObjectType at remote 0x1d087a0>, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2529
#69 0x0000003a544e964e in do_call (nk=<optimized out>, na=<optimized out>, pp_stack=0x7fffffff36c8, func=<Shiboken.ObjectType at remote 0x1d087a0>) at Python/ceval.c:4239
#70 call_function (oparg=<optimized out>, pp_stack=0x7fffffff36c8) at Python/ceval.c:4044
#71 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2666
#72 0x0000003a544ea7dd in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fffffff3818, func=<function at remote 0x101e500>) at Python/ceval.c:4107
#73 call_function (oparg=<optimized out>, pp_stack=0x7fffffff3818) at Python/ceval.c:4042
#74 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2666
#75 0x0000003a544ea7dd in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fffffff3968, func=<function at remote 0x10196e0>) at Python/ceval.c:4107
#76 call_function (oparg=<optimized out>, pp_stack=0x7fffffff3968) at Python/ceval.c:4042
#77 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2666
#78 0x0000003a544ebdbe in PyEval_EvalCodeEx (co=0x7ffff7e866b0, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, 
 defcount=0, closure=0x0) at Python/ceval.c:3253
#79 0x0000003a544ebf12 in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at Python/ceval.c:667
#80 0x0000003a5450739c in run_mod (mod=<optimized out>, filename=<optimized out>, 
 globals={'__builtins__': <module at remote 0x7ffff7f96ad0>, '__file__': 'usdView/0.7.al1.1.0/bin/usdview', '__package__': None, 'Usdviewq': <module at remote 0x7ffff1cdc440>, '__name__': '__main__', '__doc__': None}, 
 locals={'__builtins__': <module at remote 0x7ffff7f96ad0>, '__file__': 'usdView/0.7.al1.1.0/bin/usdview', '__package__': None, 'Usdviewq': <module at remote 0x7ffff1cdc440>, '__name__': '__main__', '__doc__': None}, flags=<optimized out>, arena=<optimized out>) at Python/pythonrun.c:1353
#81 0x0000003a54507470 in PyRun_FileExFlags (fp=0x7bc050, filename=0x7fffffff4dbb "usdView/0.7.al1.1.0/bin/usdview", start=<optimized out>, 
 globals={'__builtins__': <module at remote 0x7ffff7f96ad0>, '__file__': 'usdView/0.7.al1.1.0/bin/usdview', '__package__': None, 'Usdviewq': <module at remote 0x7ffff1cdc440>, '__name__': '__main__', '__doc__': None}, 
 locals={'__builtins__': <module at remote 0x7ffff7f96ad0>, '__file__': 'usdView/0.7.al1.1.0/bin/usdview', '__package__': None, 'Usdviewq': <module at remote 0x7ffff1cdc440>, '__name__': '__main__', '__doc__': None}, closeit=1, flags=0x7fffffff3ca0) at Python/pythonrun.c:1339
#82 0x0000003a5450899c in PyRun_SimpleFileExFlags (fp=0x7bc050, filename=0x7fffffff4dbb "usdView/0.7.al1.1.0/bin/usdview", closeit=1, flags=0x7fffffff3ca0)
 at Python/pythonrun.c:943
#83 0x0000003a5451a61e in Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:639
#84 0x0000003a5341ed5d in __libc_start_main (main=0x400710 <main>, argc=3, ubp_av=0x7fffffff3dc8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
 stack_end=0x7fffffff3db8) at libc-start.c:226
#85 0x0000000000400649 in _start ()
```

### System Information (OS, Hardware)
Linux, centos6
### Package Versions
USD 0.7.2
### Build Flags
defaults

**Comment by jtran56** [comment]
Filed as internal issue #142495.
