### ISSUE TITLE
Error: could not load cache

### ISSUE THREAD

**Issue by utkarshani** [PixarAnimationStudios/USD#1867]
### Description of Issue
Can you please help with it. I have attached the log file for reference. 

Thanks

  import distutils

Building with settings:
  USD source directory          C:\Users\Z004JUUU\Downloads\USD
  USD install directory         C:\USD
  3rd-party source directory    C:\USD\src
  3rd-party install directory   C:\USD
  Build directory               C:\USD\build
  CMake generator               Default
  CMake toolset                 Default
  Downloader                    curl

  Building                      Shared libraries
    Variant                     Release
    Imaging                     On
      Ptex support:             Off
      OpenVDB support:          Off
      OpenImageIO support:      Off
      OpenColorIO support:      Off
      PRMan support:            Off
    UsdImaging                  On
      usdview:                  On
    Python support              On
      Python Debug:             Off
      Python 3:                 On
    Documentation               Off
    Tests                       Off
    Examples                    On
    Tutorials                   On
    Tools                       On
    Alembic Plugin              Off
      HDF5 support:             Off
    Draco Plugin                Off
    MaterialX Plugin            Off

  Dependencies                  None
STATUS: Installing USD...
INFO: Running "cmake -DCMAKE_INSTALL_PREFIX="C:\USD" -DCMAKE_PREFIX_PATH="C:\USD" -DCMAKE_BUILD_TYPE=Release  -G "Visual Studio 16 2019" -A x64  -DPXR_PREFER_SAFETY_OVER_SPEED=ON -DPXR_ENABLE_PYTHON_SUPPORT=ON -DPXR_USE_PYTHON_3=ON -DPXR_USE_DEBUG_PYTHON=OFF -DPYTHON_EXECUTABLE="C:\Users\Z004JUUU\AppData\Local\Programs\Python\Python310\python.exe" -DPYTHON_LIBRARY="C:\Users\Z004JUUU\AppData\Local\Programs\Python\Python310\libs\python310.lib" -DPYTHON_INCLUDE_DIR="C:\Users\Z004JUUU\AppData\Local\Programs\Python\Python310\Include" -DBUILD_SHARED_LIBS=ON -DTBB_USE_DEBUG_BUILD=OFF -DPXR_BUILD_DOCUMENTATION=OFF -DPXR_BUILD_TESTS=OFF -DPXR_BUILD_EXAMPLES=ON -DPXR_BUILD_TUTORIALS=ON -DPXR_BUILD_USD_TOOLS=ON -DPXR_BUILD_IMAGING=ON -DPXR_ENABLE_PTEX_SUPPORT=OFF -DPXR_ENABLE_OPENVDB_SUPPORT=OFF -DPXR_BUILD_EMBREE_PLUGIN=OFF -DPXR_BUILD_PRMAN_PLUGIN=OFF -DPXR_BUILD_OPENIMAGEIO_PLUGIN=OFF -DPXR_BUILD_OPENCOLORIO_PLUGIN=OFF -DPXR_BUILD_USD_IMAGING=ON -DPXR_BUILD_USDVIEW=ON -DPXR_BUILD_ALEMBIC_PLUGIN=OFF -DPXR_BUILD_DRACO_PLUGIN=OFF -DPXR_ENABLE_MATERIALX_SUPPORT=OFF -DCMAKE_CXX_FLAGS="/Zm150" -DBoost_NO_BOOST_CMAKE=On -DBoost_NO_SYSTEM_PATHS=True "C:\Users\Z004JUUU\Downloads\USD""
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19042.
CMake Warning at cmake/defaults/ProjectDefaults.cmake:34 (message):
  Building USD on Windows is currently experimental.
Call Stack (most recent call first):
  CMakeLists.txt:22 (include)

-- Found Boost: C:/USD/include/boost-1_70 (found version "1.70.0")
-- Disabling boost-provided cmake config
-- Found Boost: C:/USD/include/boost-1_70 (found version "1.70.0") found components: python310
-- Found Jinja2
-- Found Boost: C:/USD/include/boost-1_70 (found version "1.70.0") found components: program_options
CMake Deprecation Warning at cmake/defaults/Packages.cmake:207 (cmake_policy):
  The OLD behavior for policy CMP0072 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:23 (include)

-- Found PySide2: with C:/Users/Z004JUUU/AppData/Local/Programs/Python/Python310/python.exe, will use C:/Users/Z004JUUU/AppData/Local/Programs/Python/Python310/Scripts/pyside2-uic.exe for pyside-uic binary
-- Found PyOpenGL
-- C++ namespace configured to (external) pxr, (internal) pxrInternal_v0_22
-- Skipping validation of gf generated code because PXR_VALIDATE_GENERATED_CODE=OFF
-- Skipping validation of sdf generated code because PXR_VALIDATE_GENERATED_CODE=OFF
-- Skipping alembic-based usddiff tests because PXR_BUILD_ALEMBIC_PLUGIN=OFF
-- Skipping Draco-based usddiff tests because PXR_BUILD_DRACO_PLUGIN=OFF
-- Skipping usdedit tests, could not find sed command.
-- Skipping hgiMetal because PXR_BUILD_GPU_SUPPORT or PXR_ENABLE_METAL_SUPPORT is OFF
-- Skipping hgiVulkan because PXR_BUILD_GPU_SUPPORT or PXR_ENABLE_VULKAN_SUPPORT is OFF
-- Skipping usdImagingGL tests because they are currently unsupported on Windows
-- Skipping usdviewq tests because they are currently unsupported on Windows
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Z004JUUU/Downloads/USD
INFO: Running "cmake --build . --config Release --target install -- /M:12"
Error: could not load cache
Traceback (most recent call last):
  File "C:\Users\Z004JUUU\Downloads\USD\build_scripts\build_usd.py", line 2311, in <module>
    dep.installer(context,
  File "C:\Users\Z004JUUU\Downloads\USD\build_scripts\build_usd.py", line 1571, in InstallUSD
    RunCMake(context, force, extraArgs)
  File "C:\Users\Z004JUUU\Downloads\USD\build_scripts\build_usd.py", line 440, in RunCMake
    Run("cmake --build . --config {config} --target install -- {multiproc}"
  File "C:\Users\Z004JUUU\Downloads\USD\build_scripts\build_usd.py", line 288, in Run
    raise RuntimeError("Failed to run '{cmd}'\nSee {log} for more details."
RuntimeError: Failed to run 'cmake --build . --config Release --target install -- /M:12'
See C:\USD\build\USD\log.txt for more details.
ERROR: Failed to run 'cmake --build . --config Release --target install -- /M:12'
See C:\USD\build\USD\log.txt for more details.
### Steps to Reproduce
1. python build_usd.py "C:\USD"

### System Information (OS, Hardware)
Windows 10

### Build Flags
[log.txt](https://github.com/PixarAnimationStudios/USD/files/8709780/log.txt)

**Comment by utkarshani** [comment]
Thanks, resolved the issue with the new release 22.05a
