### ISSUE TITLE
[usdzip] Path resolution of referenced .mtlx file fails

### ISSUE THREAD

**Issue by pablode** [PixarAnimationStudios/USD#1881]
### Description of Issue

USD files which reference .mtlx files can't be `usdzip`ed. Doing so causes an error:

```sh
--- BUILD/ToyCar ‹dev› » usdzip -a ToyCar.usdc -v ToyCar.usdz
Not recursing into sub-directories.
Creating USDZ package at 'ToyCar.usdz' containing asset @ToyCar.usdc@.
.. adding layer @/Users/pablode/tmp/guc/BUILD/ToyCar/ToyCar.usdc@ to package at path 'ToyCar.usdc'.
.. adding layer @/Users/pablode/tmp/guc/BUILD/ToyCar/ToyCar.mtlx@ to package at path '0/ToyCar.mtlx'.
Warning: in _CreateNewUsdzPackage at line 1165 of /Users/pablode/tmp/USD/pxr/usd/usdUtils/dependencies.cpp -- Failed to add temporary layer at '/var/folders/jv/dwyh17cx14s5ntkw12d3rhrc0000gn/T/ToyCar.mtlx' to the package at path 'ToyCar.usdz'.
.. adding file '/Users/pablode/tmp/guc/BUILD/ToyCar/ToyCar_emissive.png' to package at path '0/ToyCar_emissive.png'.
.. adding file '/Users/pablode/tmp/guc/BUILD/ToyCar/ToyCar_normal.png' to package at path '0/ToyCar_normal.png'.
.. adding file '/Users/pablode/tmp/guc/BUILD/ToyCar/ToyCar_basecolor.png' to package at path '0/ToyCar_basecolor.png'.
.. adding file '/Users/pablode/tmp/guc/BUILD/ToyCar/ToyCar_occlusion_roughness_metallic.png' to package at path '0/ToyCar_occlusion_roughness_metallic.png'.
.. adding file '/Users/pablode/tmp/guc/BUILD/ToyCar/ToyCar_clearcoat.png' to package at path '0/ToyCar_clearcoat.png'.
.. adding file '/Users/pablode/tmp/guc/BUILD/ToyCar/Fabric_occlusion.png' to package at path '0/Fabric_occlusion.png'.
.. adding file '/Users/pablode/tmp/guc/BUILD/ToyCar/Fabric_normal.png' to package at path '0/Fabric_normal.png'.
.. adding file '/Users/pablode/tmp/guc/BUILD/ToyCar/Fabric_baseColor.png' to package at path '0/Fabric_baseColor.png'.
Traceback (most recent call last):
  File "/Users/pablode/tmp/USD/INSTALL/bin/usdzip", line 295, in <module>
    sys.exit(main())
  File "/Users/pablode/tmp/USD/INSTALL/bin/usdzip", line 254, in main
    success = success and UsdUtils.CreateNewUsdzPackage(
pxr.Tf.ErrorException:
  Error in 'pxrInternal_v0_22__pxrReserved__::UsdZipFileWriter::AddFile' at line 932 in file /Users/pablode/tmp/USD/pxr/usd/usd/zipFile.cpp : 'Failed to map '/var/folders/jv/dwyh17cx14s5ntkw12d3rhrc0000gn/T/ToyCar.mtlx': No such file or directory'
```

### Steps to Reproduce

1. download and unzip [ToyCar.zip](https://github.com/PixarAnimationStudios/USD/files/8760828/ToyCar.zip)
2. usdzip -a ToyCar.usdc -v ToyCar.usdz
3. observe error

### System Information (OS, Hardware)
Windows & MacOS

### Build Flags
OIIO and MaterialX

**Comment by jilliene** [comment]
Filed as internal issue #USD-7387

**Comment by spiffmon** [comment]
Hi @pablode ,
   The issue you are running into here is that when you ask `usdzip` to first _localize_ your assets with the `-a` flag, it needs to rewrite certain assetPaths within the localized assets themselves, and while USD knows how to **read** Mtlx files (even within a usdz package), it does not know how to **write** them.  It may be awhile before we have a robust solution for that specific problem, but I can offer two workarounds.
1. Prior to running usdzip, convert all of your mtlx files to usd files, using `usdcat -o materials.usd materials.mtlx` , and making your usd files reference materials.usd instead of materials.mtlx . This is the preferred, long-term solution, because it will produce the fastest-loading and lightest usdz package.  The primary downside is that you lose the mtlx files, which applications that only read mtlx and not usd could use.  But then, if they can't read usd you wouldn't be able to get the geometry, anyway.
2. If all of the files that comprise your asset are already in the same directory (or subdirs of that directory), then you can use the "simple" form of usdzip, **without** the `-a` option, instead just listing out on the command line all the files to include (the root usd layer must come first, the order of other files is irrelevant).  The usdzip does not need to mutate any of the files, and the mtlx files will just populate the package.
