### ISSUE TITLE
Installing TBB in MacOs 12.4 failed

### ISSUE THREAD

**Issue by LaurentGarcia** [PixarAnimationStudios/USD#1884]
### Description of Issue
Hello ,

When I try to install USD in the last MacOS version is freezing at Installing TBB... If I cancel it I got:
  File "/Users/laurenmanuelgarciacarro/Code/repositories/USD/build_scripts/build_usd.py", line 2312, in <module>
    dep.installer(context, 
  File "/Users/laurenmanuelgarciacarro/Code/repositories/USD/build_scripts/build_usd.py", line 874, in InstallTBB
    InstallTBB_LinuxOrMacOS(context, force, buildArgs)
  File "/Users/laurenmanuelgarciacarro/Code/repositories/USD/build_scripts/build_usd.py", line 905, in InstallTBB_LinuxOrMacOS
    Run('make -j{procs} {buildArgs}'
  File "/Users/laurenmanuelgarciacarro/Code/repositories/USD/build_scripts/build_usd.py", line 272, in Run
    l = p.stdout.readline().decode(GetLocale(), 'replace')

### Steps to Reproduce
1. git clone last USD repo2. 
2. python build_scripts/build_usd.py /opt/local/USD3. 

#System Information (OS, Hardware)

MacOs Monterrey 12.4
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2.4 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	256 KB
  L3 Cache:	16 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB
  System Firmware Version:	1731.120.10.0.0 (iBridge: 19.16.15071.0.0,0)
  OS Loader Version:	540.120.3~6

**Comment by jilliene** [comment]
Filed as internal issue #USD-7399

**Comment by creijon** [comment]
Laurent, can you run with python3 please?  python 2.7 has been deprecated in macOS since 12.3

**Comment by LaurentGarcia** [comment]
Same results:

^CTraceback (most recent call last):
  File "/Users/laurenmanuelgarciacarro/Code/repositories/USD/build_scripts/./build_usd.py", line 2312, in <module>
    dep.installer(context, 
  File "/Users/laurenmanuelgarciacarro/Code/repositories/USD/build_scripts/./build_usd.py", line 874, in InstallTBB
    InstallTBB_LinuxOrMacOS(context, force, buildArgs)
  File "/Users/laurenmanuelgarciacarro/Code/repositories/USD/build_scripts/./build_usd.py", line 905, in InstallTBB_LinuxOrMacOS
    Run('make -j{procs} {buildArgs}'
  File "/Users/laurenmanuelgarciacarro/Code/repositories/USD/build_scripts/./build_usd.py", line 272, in Run
    l = p.stdout.readline().decode(GetLocale(), 'replace')
KeyboardInterrupt

**Comment by davidgyu** [comment]
I've just built the current USD dev branch on macOS 11, 12, and 13 with Python 3 and didn't have any trouble with the TBB build.

Is this still a problem for you? Thanks!

**Comment by sunyab** [comment]
Closing out old issue, please file a new issue if this is still a problem in recent releases. Thanks!
