### ISSUE TITLE
Resolver/schema examples raise Python ImportError on Windows 10 (usd-22.05)

### ISSUE THREAD

**Issue by eddiehoyle** [PixarAnimationStudios/USD#1920]
### Description of Issue
I get Python ImportErrors when importing these examples on Windows after a fresh build:
* [usdResolverExample](https://github.com/PixarAnimationStudios/USD/tree/release/extras/usd/examples/usdResolverExample)
* [usdSchemaExamples](https://github.com/PixarAnimationStudios/USD/tree/release/extras/usd/examples/usdSchemaExamples)

I've been trying to build these for reference so I can start on a custom resolver that works with our production tracking system.

### Steps to Reproduce
The error:
```python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pxr import UsdResolverExample
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\eddie.hoyle\usd-22.05\lib\python\pxr\UsdResolverExample\__init__.py", line 25, in <module>
    Tf.PreparePythonModule()
  File "C:\Users\eddie.hoyle\usd-22.05\lib\python\pxr\Tf\__init__.py", line 89, in PreparePythonModule
    "." + moduleName, f_locals["__name__"])
  File "C:\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified module could not be found.
```
> **Note:** The same happens both with system and virtualenv Python

Library imports work fine:
```python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pxr import Usd, Sdf, Gf, UsdGeom # etc
>>>
```

### System Information (OS, Hardware)
* Windows 10 Pro, Version 10.0.18363 Build 18363

### Package Versions
**Note:** I don't have external internet access when building USD so I use a slightly modified `build_usd.py` that points to local copies of these archives:
| Package | Archive   |
|---------|-----------------------------|
| Alembic | 1.7.10.zip                  |
| Boost   | boost_1_70_0.tar.gz         |
|hdf5| hdf5-1.10.0-patch1.zip      |
|tbb| tbb2018_20180822oss_win.zip |
|zlib| v1.2.11.zip                 |
|OpenEXR| v2.3.0.zip                  |
|OpenSubdiv| v3_4_4.zip                  |
|OpenImageIO|Release-2.1.16.0.zip|
|JPEG|1.5.1.zip|
|TIFF|libtiff-Release-v4-0-7.tar.gz|
|png|v1.6.29.tar.gz|

### Build Flags
Built using a Python 3.7 virtual environment with packages installed:
* jinja2
* pyopengl
* numpy
* pyside2

Full build output:
```python
(venv) PS C:\Users\eddie.hoyle\ClionProjects\external\USD-22.05>python .\build_scripts\build_usd.py C:\Users\eddie.hoyle\usd-22.05 --src C:\Users\eddie.hoyle\ClionProjects\external\USD-22.05\build_source --openimageio --hdf5 --alembic --build-python-info C:\Users\eddie.hoyle\ClionProjects\external\USD-22.05\venv\Scripts\python.exe C:\Python37\include C:\Python37\libs\python37.lib 3.7

Building with settings:
  USD source directory          C:\Users\eddie.hoyle\ClionProjects\external\USD-22.05
  USD install directory         C:\Users\eddie.hoyle\usd-22.05
  3rd-party source directory    C:\Users\eddie.hoyle\ClionProjects\external\USD-22.05\build_source
  3rd-party install directory   C:\Users\eddie.hoyle\usd-22.05
  Build directory               C:\Users\eddie.hoyle\usd-22.05\build
  CMake generator               Default
  CMake toolset                 Default
  Downloader                    curl

  Building                      Shared libraries
    Variant                     Release
    Imaging                     On
      Ptex support:             Off
      OpenVDB support:          Off
      OpenImageIO support:      On
      OpenColorIO support:      Off
      PRMan support:            Off
    UsdImaging                  On
      usdview:                  On
    Python support              On
      Python Debug:             Off
      Python 3:                 On
    Documentation               Off
    Tests                       Off
    Examples                    On
    Tutorials                   On
    Tools                       On
    Alembic Plugin              On
      HDF5 support:             On
    Draco Plugin                Off
    MaterialX Plugin            Off

  Dependencies                  None
STATUS: Installing USD...

Success! To use USD, please ensure that you have:

    The following in your PYTHONPATH environment variable:
    C:\Users\eddie.hoyle\usd-22.05\lib\python

    The following in your PATH environment variable:
    C:\Users\eddie.hoyle\usd-22.05\bin
    C:\Users\eddie.hoyle\usd-22.05\lib
```

**Comment by sunyab** [comment]
Could you try adding `C:\Users\eddie.hoyle\usd-22.05\share\usd\examples` to your PATH and see if that helps? I'm guessing Python isn't finding the necessary usdResolverExample and usdSchemaExamples DLL when trying to import the Python bindings.

**Comment by eddiehoyle** [comment]
@sunyab, that was it! I added this `PATH`:
```
C:\Users\eddie.hoyle\usd-22.05\share\usd\examples\plugin
```
And the import works:
```
(venv) PS C:\Users\eddie.hoyle\usd-22.05> python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pxr import UsdResolverExample
>>> from pxr import UsdSchemaExamples
>>>
```
Thank you for the help!
