### ISSUE TITLE
Errors in Tf_AtomicRenameFileOver on windows due to handles being temporarily held

### ISSUE THREAD

**Issue by pmolodo** [PixarAnimationStudios/USD#2141]
### Description of Issue

On windows, we have recurring issues with file renames failing, because some other process temporarily has a handle to the file that will be written over.  (Likely either the Windows indexing service or a virus protection program).

The handles are generally not taken for a very long time, so adding short retry interval (1-2s) to `Tf_AtomicRenameFileOver` would probably fix the issue.  I'd be willing to make a PR for this myself, but I'd like to know:

a) If you'd be open to accepting such a change
b) If you'd want apply retry logic to all operating systems, or only Windows

### Steps to Reproduce

We generally see the failures when running the test suite on Windows.  The frequency per run is low, but high enough that at the rate at which our CI system runs the test suite, it pops up every couple days.  Some example failures:

**testUsdUtilsStitchClips**
```
======================================================================
ERROR: test_CustomSetName (__main__.TestUsdUtilsStitchClips)
Test authoring with a custom set name 'bob'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/b/w/1cb35280caeac9a1/_install/py37.windows-x86_64.nv-usd.debug/tests/testUsdUtilsStitchClips", line 199, in test_CustomSetName
    clipSet='bob')
pxr.Tf.ErrorException:
  Error in 'pxrInternal_v0_20__pxrReserved__::TfSafeOutputFile::Close' at line 86 in file C:\b\w\1cb35280caeac9a1\USD\pxr\base\tf\safeOutputFile.cpp : 'Failed to rename temporary file 'c:\b\t\buildTmp\tmpgo915b8q/customSetName.o2tmbs' to 'c:\b\t\buildTmp\tmpgo915b8q\customSetName.usd': Access is denied.
```

**testUsdMetadata**
```
======================================================================
ERROR: test_ComposedListOpMetadata (__main__.TestUsdMetadata)
Tests composition of list op-valued metadata fields
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/b/w/1cb35280caeac9a1/_install/py37.windows-x86_64.nv-usd.release/tests/testUsdMetadata", line 801, in test_ComposedListOpMetadata
    weakListOp, strongListOp, expectedListOp)
  File "C:/b/w/1cb35280caeac9a1/_install/py37.windows-x86_64.nv-usd.release/tests/testUsdMetadata", line 722, in _TestComposition
    s = Usd.Stage.CreateNew("TestComposedListOpMetadata."+fmt)
pxr.Tf.ErrorException:
  Error in 'pxrInternal_v0_20__pxrReserved__::SdfTextFileFormat::WriteToFile' at line 327 in file C:\b\w\1cb35280caeac9a1\USD\pxr\usd\sdf\textFileFormat.cpp : 'Failed to rename temporary file 'c:\b\t\buildTmp\tmpdpm8h2of/TestComposedListOpMetadata.l1qnep' to 'c:\b\t\buildTmp\tmpdpm8h2of\TestComposedListOpMetadata.usda': Access is denied.
```

### System Information (OS, Hardware)

Windows 10 (with Windows Defender enabled)

### Package Versions

USD v22.11

**Comment by sunyab** [comment]
Filed as internal issue #USD-7841

**Comment by FlorianZ** [comment]
Thanks @pmolodo. We discussed this internally and agree that a tactical retry (only on Windows!) is a reasonable workaround here, and we'd be happy to consider such a change! Would you be willing to take a stab at that and shoot over a PR? Thanks again!

**Comment by pmolodo** [comment]
Thanks, will do when I have a chance...

**Comment by pmolodo** [comment]
FYI, I have an fix for this that I'm currently reviewing internally.  Once I've confirmed it's working there, I'll make a PR for it here...

**Comment by pmolodo** [comment]
This has been working well in our own internal branch for a while, so finally made a PR for it...

**Comment by sunyab** [comment]
This was addressed by f3d48bc in the 26.05 release, closing this out.
