### ISSUE TITLE
`Boost Python` binding fails to run when using `python 3.11`

### ISSUE THREAD

**Issue by somyungoh** [PixarAnimationStudios/USD#2299]
### Description of Issue
When I build using `build_usd.py`, I fail to use USD python bindings with `python 3.11` having an error:
`SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function`

This seems to be [fixed](https://github.com/boostorg/python/issues/400) in  `boost 1.81.0`, however, the script targets `boost 1.78.0` or `1.70.0`.

I am not sure if targeting & making it compatible with `1.81.0` is in the roadmap though.

### Steps to Reproduce
1. Run any python bindings with `python 3.11`. eg:
```py
from pxr import Usd, UsdGeom
```

### System Information (OS, Hardware)
MacOS (x86-64), Monterey

### Package Versions
v23.02

### Build Flags
None

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8040

**Comment by FlorianZ** [comment]
@somyungoh unfortunately, boost 1.81 is not on the VFX reference platform yet (at least not as of CY2023), so it will be a while until we official support 1.81. Having said that, we are happy to consider contributions if there is a fix to make the build script compatible with optionally building against 1.81.

**Comment by somyungoh** [comment]
Thank you @FlorianZ for letting us know!

**Comment by julienbfabre** [comment]
I am having the same issue, @somyungoh i it's marked as completed but i see no recent commit in the repo, what is the way to fix this?

**Comment by elvismarus** [comment]
Hi,

I have the same issue when trying to run this command:
D:\Pixar>usdview extras\usd\tutorials\convertingLayerFormats\Sphere.usd

Warning: in Tf_PyLoadScriptModule at line 117 of D:\Pixar\pxr\base\tf\pyUtils.cpp -- Import failed for module 'pxr.Usd'!
Traceback (most recent call last):
  File "D:\PixarInstalled\lib\python\pxr\Usd\__init__.py", line 25, in <module>
    Tf.PreparePythonModule()
  File "D:\PixarInstalled\lib\python\pxr\Tf\__init__.py", line 88, in PreparePythonModule
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function
Warning: in Tf_PyLoadScriptModule at line 117 of D:\Pixar\pxr\base\tf\pyUtils.cpp -- Import failed for module 'pxr.UsdGeom'!
Traceback (most recent call last):
  File "D:\PixarInstalled\lib\python\pxr\UsdGeom\__init__.py", line 25, in <module>
    Tf.PreparePythonModule()
  File "D:\PixarInstalled\lib\python\pxr\Tf\__init__.py", line 88, in PreparePythonModule
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: No to_python (by-value) converter found for C++ type: class pxrInternal_v0_23__pxrReserved__::UsdTimeCode
Traceback (most recent call last):
  File "D:\PixarInstalled\bin\usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
  File "D:\PixarInstalled\lib\python\pxr\Usdviewq\__init__.py", line 32, in <module>
    from .qt import QtWidgets, QtCore
  File "D:\PixarInstalled\lib\python\pxr\Usdviewq\qt.py", line 42, in <module>
    PySideModule = GetPySideModule()
                   ^^^^^^^^^^^^^^^^^
  File "D:\PixarInstalled\lib\python\pxr\Usdviewq\qt.py", line 31, in GetPySideModule
    from . import attributeValueEditorUI
  File "D:\PixarInstalled\lib\python\pxr\Usdviewq\attributeValueEditorUI.py", line 1
    /********************************************************************************
    ^
SyntaxError: invalid syntax

Could you please let me know what can be the root-cause?
Thank you!
