### ISSUE TITLE
Unsupported Hgi backend: OpenGL

### ISSUE THREAD

**Issue by adro79** [PixarAnimationStudios/USD#2430]
### Description of Issue

I managed to build USD with all components enabled in Arch Linux. When launching usdview I get a black viewport if Vulkan support is enabled when building.
![Screenshot_20230510_083828](https://github.com/PixarAnimationStudios/USD/assets/57686179/ab02bfb7-9905-436e-84e3-e5fdfba7975a)

Here's the full output when launching usdview:
```
Warning: in Tf_PyLoadScriptModule at line 117 of /home/adro/Applications/AUR/usd/src/USD/pxr/base/tf/pyUtils.cpp -- Import failed for module 'pxr.Usd'!
Traceback (most recent call last):
  File "/usr/share/usd/lib/python/pxr/Usd/__init__.py", line 25, in <module>
    Tf.PreparePythonModule()
  File "/usr/share/usd/lib/python/pxr/Tf/__init__.py", line 88, in PreparePythonModule
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function
Warning: in Tf_PyLoadScriptModule at line 117 of /home/adro/Applications/AUR/usd/src/USD/pxr/base/tf/pyUtils.cpp -- Import failed for module 'pxr.UsdGeom'!
Traceback (most recent call last):
  File "/usr/share/usd/lib/python/pxr/UsdGeom/__init__.py", line 25, in <module>
    Tf.PreparePythonModule()
  File "/usr/share/usd/lib/python/pxr/Tf/__init__.py", line 88, in PreparePythonModule
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: No to_python (by-value) converter found for C++ type: pxrInternal_v0_23__pxrReserved__::UsdTimeCode
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::Tf_TypedPyEnumWrapper<pxrInternal_v0_23__pxrReserved__::UsdListPosition> already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::UsdListPosition already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::Tf_TypedPyEnumWrapper<pxrInternal_v0_23__pxrReserved__::UsdLoadPolicy> already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::UsdLoadPolicy already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::UsdGeomBBoxCache already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::UsdGeomConstraintTarget already registered; second conversion method ignored.
ERROR: Usdview encountered an error while rendering.
	Error in 'pxrInternal_v0_23__pxrReserved__::HgiInterop::TransferToApp' at line 75 in file /home/adro/Applications/AUR/usd/src/USD/pxr/imaging/hgiInterop/hgiInterop.cpp : 'Unsupported Hgi backend: OpenGL'
```

### Steps to Reproduce
1. Build USD with Vulkan Support
2. Launch usdview

### System Information (OS, Hardware)
- Arch Linux
- Nvidia RTX 3090

### Package Versions
- Vulkan 1.2.170.0
- Python 3.11.3
- Boost 1.78
- TBB 2019.6

### Build Flags
```
    -DCMAKE_INSTALL_PREFIX:PATH=/usr/share/usd
    -DPXR_BUILD_TESTS=ON
    -DBOOST_ROOT="${srcdir}"/boost
    -DTBB_ROOT_DIR="${srcdir}"/tbb2019/usr
    -DBoost_NO_BOOST_CMAKE=ON
    -DPXR_BUILD_DOCUMENTATION=ON
    -DPXR_ENABLE_GL_SUPPORT=ON
    -DPXR_BUILD_GPU_SUPPORT=ON
    -DPXR_ENABLE_VULKAN_SUPPORT=ON
    -DPXR_BUILD_ALEMBIC_PLUGIN=ON
    -DPXR_BUILD_EMBREE_PLUGIN=ON
    -DPXR_ENABLE_OSL_SUPPORT=ON
    -DPXR_BUILD_DRACO_PLUGIN=ON
    -DBUILD_SHARED_LIBS=ON
    -DPXR_MALLOC_LIBRARY:path=/usr/lib/libjemalloc.so
    -DPXR_VALIDATE_GENERATED_CODE=ON
```

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8315

**Comment by davidgyu** [comment]
The HgiVulkan implementation is incomplete and not ready to be used and we recommend not enabling Vulkan support at the moment.

Agree that this error message from HgiInterop seems incorrect and we'll look into addressing that as part of our ongoing Vulkan work.

Thanks!

**Comment by adro79** [comment]
Thanks to you for replying, is there a roadmap I can look at to see the progress of the implementation?

**Comment by iceteaa** [comment]
> SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function

This issue is caused by  boost 1.78 in  python 3.11 has issue
u can use boost larger than1.83 or del Py_TPFLAGS_HAVE_GC in boost 1.78 enum c file
