### ISSUE TITLE
Custom Schema  already has a defined C++ type; cannot redefine

### ISSUE THREAD

**Issue by jmacey** [PixarAnimationStudios/USD#2539]
I am building a custom schema based on the examples for a new set of lectures for my students. I have managed to add a new folder and build the schema plugin fine. 
When I then import I get the following error

```
 python -c "from pxr import Ncca"
Coding Error: in _DefineCppType at line 964 of /Volumes/teaching/USD/pxr/base/tf/type.cpp -- TfType 'NCCALocator' already has a defined C++ type; cannot redefine
```

The schema is

```
#usda 1.0
(
    """ a simple Locator Schema    """
    subLayers = [
        @usd/schema.usda@
    ]
) 

over "GLOBAL" (
    customData = {
        string libraryName       = "Ncca"
        string libraryPath       = "."
        string libraryPrefix     = "NCCA"
    }
) {
}

class "SimpleLocator" (
    doc = """An example of an untyped schema prim. Note that it does not 
    specify a typeName"""
    # IsA schemas should derive from </Typed>, which is defined in the sublayer
    # usd/lib/usd/schema.usda.
    inherits = </Typed>
    customData = {
        # Provide a different class name for the C++ and python schema classes.
        # This will be prefixed with libraryPrefix.
        # In this case, the class name becomes locator.
        string className = "Locator"
        }
    )  
{
    float scale = 1.0 (
        doc = "scale of the locator default value 1.0f"
    )
}
```

I does still seem to partially work as I can do

```
from pxr import Ncca
locator=Ncca.Locator()
locator.GetSchemaAttributeNames()
['scale']
```

However if I try (which I think should work)

```
 locator.Get('scale')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Accessed schema on invalid prim
>>> locator.GetScaleAttr()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Accessed schema on invalid prim
```
I get these errors not sure If I still don't understand what I am doing (possible!) or if I am missing something in the build steps. The demos for schemas are a little unclear so hoping to get some help (I will write it all up as an example to contribute back once done)

I have noticed (for example) that the usdGenSchema tool likes to convert things to use certain cases (i used NCCA for the libraryName for example which is seemed to auto convert to Ncca which confused me for ages) so I'm guessing it something like this that is not documented. :-) 

Thanks

Jon

**Comment by nvmkuruc** [comment]
I'm not sure about the import error, but looking at the code you provided, it looks like the schema isn't bound a prim.  I'd expect `bool(locator)` to return `False`.  There's a shortcut for quickly creating a schema bound to a prim on a stage.

```
from pxr import Usd
from pxr import UsdGeom # replace with your schema domain

stage = Usd.Stage.CreateInMemory()
# replace with your schema
xform = UsdGeom.Xform.Define(stage, "/my_new_prim")
print(bool(xform))
```

Hope that snippet helps.

**Comment by jmacey** [comment]
Thanks, didn't work but gives me something to look at.

```
from pxr import Usd,Ncca
>>> stage = Usd.Stage.CreateInMemory()
Warning: in Tf_PyLoadScriptModule at line 117 of /Volumes/teaching/USD/pxr/base/tf/pyUtils.cpp -- Import failed for module 'pxr.NCCA'!
ModuleNotFoundError: No module named 'pxr.NCCA'
>>> loc=Ncca.Locator.Define(stage,"test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Locator' has no attribute 'Define'
```
Still looks like a naming / case thing in the schema exampes it has 

```
over "GLOBAL" (
    customData = {
        string libraryName       = "usdSchemaExamples"
        string libraryPath       = "."
        string libraryPrefix     = "UsdSchemaExamples"
    }
) 
```

which I'm trying to replace with my own names. Note the lowercase u  at the start which seems to be significant but not documented!  Late night now so will look in the morning.

**Comment by nvmkuruc** [comment]
I suspect `SimpleLocator` isn't a concrete typed schema which is why `Define` is missing.  As a next step, I might try 

```
class SimpleLocator "SimpleLocator" { ... }
```

https://github.com/PixarAnimationStudios/OpenUSD/blob/release/pxr/usd/usdGeom/schema.usda#L920 as a reference for another concrete typed schema definition.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8499

**Comment by jmacey** [comment]
Thanks @nvmkuruc  that fixed one of the errors and I can now define and save my prim, still get the defined c++ type but I can at least start working on some examples.

**Comment by jmacey** [comment]
For info this is what I have so far. https://nccastaff.bournemouth.ac.uk/jmacey/post/USDSchema/USDSchema/ very steep learning curve :-)

**Comment by TobyGilbert** [comment]
@jmacey I ran into the same thing following your guide.  I was able to resolve this by removing locator.cpp from PYMODULE_CPPFILES in CMakeLists.cpp.
