### ISSUE TITLE
ERROR: USD does not support Python 2. Use a supported version.

### ISSUE THREAD

**Issue by psqv** [PixarAnimationStudios/USD#2676]
I´m getting the following error trying to install OpenUSD:

ERROR: USD does not support Python 2. Use a supported version.

Full output:

peder@MacBook-Pro-14 ~ % USD/build_scripts/build_usd.py /opt/local/USD
USD/build_scripts/build_usd.py: line 27: import: command not found
USD/build_scripts/build_usd.py: line 29: syntax error near unexpected token `"ERROR: USD does not support Python 2. Use a supported version "'
USD/build_scripts/build_usd.py: line 29: `    sys.exit("ERROR: USD does not support Python 2. Use a supported version "'
peder@MacBook-Pro-14 ~ % python --version
Python 3.11.5

MacOS Sonoma 14.0 Beta (23A5328b), Python 3.11.5 (installed with .pkg installer from https://www.python.org/downloads/)

I have tried removing/re-installing Python, installing it via homebrew, managing with pyenv etc but I still get this error every time I try to run the installation script.

Any ideas on how I can fix this?

![SCR-20230912-bnz](https://github.com/PixarAnimationStudios/OpenUSD/assets/24634817/b4e5a7c7-f092-476e-9bd2-662f626eaaec)

**Comment by sunyab** [comment]
Per the instructions in the [README.md](https://github.com/PixarAnimationStudios/OpenUSD#macos), you'll need to invoke the build script like:

`python USD/build_scripts/build_usd.py /opt/local/USD`

Right now zsh is trying to run the .py file as a shell script, which is why you're getting syntax errors.

**Comment by dgovil** [comment]
@sunyab , do you think we should maybe add a shebang to the `build_usd.py` so it defaults to `/usr/bin/env python3` ?

**Comment by sunyab** [comment]
@dgovil Yes, I think that's a good idea and more doable now that we only support Python 3. I wasn't sure if we'd have to do something special for Windows but it looks like the Python launcher on that platform supports shebangs too.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8690

**Comment by psqv** [comment]
> python USD/build_scripts/build_usd.py /opt/local/USD

Thanks for the clarification. I need to work on my copy/paste skills, obviously! 🙈

**Comment by psqv** [comment]
> Per the instructions in the [README.md](https://github.com/PixarAnimationStudios/OpenUSD#macos), you'll need to invoke the build script like:
> 
> `python USD/build_scripts/build_usd.py /opt/local/USD`
> 
> Right now zsh is trying to run the .py file as a shell script, which is why you're getting syntax errors.

Installed fine when I included the python reference (duh!), but still getting errors trying to run usdview:

`peder@MacBook-Pro-14 ~ % usdview USD/extras/usd/tutorials/convertingLayerFormats/Sphere.usda
Warning: in Tf_PyLoadScriptModule at line 117 of /Users/peder/USD/pxr/base/tf/pyUtils.cpp -- Import failed for module 'pxr.Usd'!
Traceback (most recent call last):
  File "/opt/local/USD/lib/python/pxr/Usd/__init__.py", line 25, in <module>
    Tf.PreparePythonModule()
  File "/opt/local/USD/lib/python/pxr/Tf/__init__.py", line 88, in PreparePythonModule
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peder/.pyenv/versions/3.11.5/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function
Warning: in Tf_PyLoadScriptModule at line 117 of /Users/peder/USD/pxr/base/tf/pyUtils.cpp -- Import failed for module 'pxr.UsdGeom'!
Traceback (most recent call last):
  File "/opt/local/USD/lib/python/pxr/UsdGeom/__init__.py", line 25, in <module>
    Tf.PreparePythonModule()
  File "/opt/local/USD/lib/python/pxr/Tf/__init__.py", line 88, in PreparePythonModule
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peder/.pyenv/versions/3.11.5/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: No to_python (by-value) converter found for C++ type: pxrInternal_v0_23__pxrReserved__::UsdTimeCode
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::Tf_TypedPyEnumWrapper<pxrInternal_v0_23__pxrReserved__::UsdListPosition> already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::UsdListPosition already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::Tf_TypedPyEnumWrapper<pxrInternal_v0_23__pxrReserved__::UsdLoadPolicy> already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::UsdLoadPolicy already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::UsdGeomBBoxCache already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for pxrInternal_v0_23__pxrReserved__::UsdGeomConstraintTarget already registered; second conversion method ignored.
qt.qpa.openglcontext: Failed to create NSOpenGLContext
QRhiGles2: Failed to create temporary context
qt.qpa.openglcontext: Failed to create NSOpenGLContext
QRhiGles2: Failed to create context
Failed to create QRhi for QBackingStoreRhiSupport
zsh: segmentation fault  usdview USD/extras/usd/tutorials/convertingLayerFormats/Sphere.usda
peder@MacBook-Pro-14 ~ % 
`

![SCR-20230913-ctu](https://github.com/PixarAnimationStudios/OpenUSD/assets/24634817/7143b168-ead6-4120-ba97-6de8c38f56fb)

**Comment by psqv** [comment]
Fixed by using the following build arguments:

python build_scripts/build_usd.py /opt/local/USD --build-args USD,"-DPXR_PY_UNDEFINED_DYNAMIC_LOOKUP=ON"

**Comment by sunyab** [comment]
@psqv Oh hm, that shouldn't be necessary -- are you running a homebrew or conda-installed Python by any chance?

**Comment by Garfield9986** [comment]
openusd is now fully compiled with python3 and above. You can create a python3 virtual environment with anaconda and follow the official instructions.
