### ISSUE TITLE
USD monolithic build on Rocky9.2 with embree fails when trying to run usdview

### ISSUE THREAD

**Issue by shdwdln** [PixarAnimationStudios/USD#2732]
### Steps to Reproduce
1. Build USD 23.08 as monolithic with embree

### System Information (OS, Hardware)
Rocky 9.2 (Blue Onlyx)
### Package Versions
python3.9 -m pip install PyOpenGL PySide2

### Build Flags
python3.9 build_scripts/build_usd.py --embree --build-monolithic $PWD/install

I try to run usdview and I get the error (after setting PATH and PYTHONPATH) 
ImportError: libembree3.so.3: cannot open shared object file: No such file or directory

If I build again and remove the --embree argument then usdview runs fine

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8831

**Comment by spiffmon** [comment]
Thanks, @shdwdln .  We are in the process of moving our infrastructure over to Alma, which should be similar enough to Rocky that we could diagnose (and need to) and address such issues.  We're not quite there yet, but we'll keep this queued for then.

**Comment by dinelanthony** [comment]
Not sure if this will fix it, but have you considered building with PySide6 instead? I am also using 23.08 with Python 3.9.13 and PySide6. I previously had issues with PySide2 so this could help

**Comment by shdwdln** [comment]
I did create a venv so I could just install: PyOpenGL PySide6 Jinja2 numpy
and everything built fine but when I ran usdview it launched a window, closed the window, and launched another window (usdview) with the file requested. I did get this output

(OpenUSD_PySide6) [dillon@rocky9pro OpenUSD]$ ./install/bin/usdview /home/dillon/USD_Files/omniAnimCube.usda
Traceback (most recent call last):
  File "/home/dillon/DEV/OpenUSD_PySide6/OpenUSD/install/lib/python/pxr/Usdviewq/stageView.py", line 2361, in _primSelectionChanged
    self.updateSelection()
  File "/home/dillon/DEV/OpenUSD_PySide6/OpenUSD/install/lib/python/pxr/Usdviewq/stageView.py", line 1358, in updateSelection
    renderer = self._getRenderer()
  File "/home/dillon/DEV/OpenUSD_PySide6/OpenUSD/install/lib/python/pxr/Usdviewq/stageView.py", line 941, in _getRenderer
    if self.context().isValid():
AttributeError: 'NoneType' object has no attribute 'isValid'

**Comment by shdwdln** [comment]
When I installed embree and set it I got the same error.

```
Warning: in _GetResolvedDomeLightEnvironmentFilePath at line 288 of /home/dillon/DEV/OpenUSD_PySide6/OpenUSD/pxr/imaging/hdSt/simpleLightingShader.cpp -- Dome light has no texture asset path.
Traceback (most recent call last):
  File "/home/dillon/DEV/OpenUSD_PySide6/OpenUSD/install/lib/python/pxr/Usdviewq/appController.py", line 1453, in <lambda>
    self._rendererPluginChanged(pluginType))
  File "/home/dillon/DEV/OpenUSD_PySide6/OpenUSD/install/lib/python/pxr/Usdviewq/appController.py", line 1414, in _rendererPluginChanged
    if not self._stageView.SetRendererPlugin(plugin):
  File "/home/dillon/DEV/OpenUSD_PySide6/OpenUSD/install/lib/python/pxr/Usdviewq/stageView.py", line 988, in SetRendererPlugin
    if self._renderer.SetRendererPlugin(plugId):
pxr.Tf.ErrorException: 
	Error in 'pxrInternal_v0_23__pxrReserved__::PlugPlugin::_Load' at line 260 in file /home/dillon/DEV/OpenUSD_PySide6/OpenUSD/pxr/base/plug/plugin.cpp : 'Failed to load plugin 'hdEmbree': libembree3.so.3: cannot open shared object file: No such file or directory in '/home/dillon/DEV/OpenUSD_PySide6/OpenUSD/install/plugin/usd/hdEmbree.so''
	Error in 'pxrInternal_v0_23__pxrReserved__::UsdImagingGLEngine::SetRendererPlugin' at line 968 in file /home/dillon/DEV/OpenUSD_PySide6/OpenUSD/pxr/usdImaging/usdImagingGL/engine.cpp : 'Invalid plugin id or plugin is unsupported: HdEmbreeRendererPlugin'

```
