### ISSUE TITLE
Entry point for SdfLayerTree?

### ISSUE THREAD

**Issue by adalast** [PixarAnimationStudios/USD#2818]
### Description of Issue
Working with Houdini Hython for this project.

I am attempting to build a parsing software for nested USD trees and I am running into a few issues.  Firstly, I am walking over UsdStage.GetUsedLayers() to retrieve what appears to be the current set of active layers within the scene.  I would much prefer to be able to the SdfLayerTree to walk it, as the description indicates that it is ideally suited for this sort of activity.  My use case would benefit from generating the layer dependency path for the current layer, but I cannot see a viable way to get at that information as I cannot see a way to trigger USD to generate a LayerTree object, nor can I find anywhere where one would already have been created.  There are methods to step up from the current node of the tree to the associated layer, but I can find no methods on SdfStage, UsdPrim, nor SdfLayer which would give the reverse, stepping into the tree.

I always will have a finite definition as to the root of the tree, as Houdini requires that the root file be loaded from a parm.

### System Information (OS, Hardware)
Windows 10

### Package Versions
Houdini 19.5.368
Python 3.9
not sure on pxr version, as it does not include a __version__ attribute and I cannot suss it out.

**Comment by spiffmon** [comment]
`GetUsedLayers()` returns **all** the layers that the currently composed stage consumes - that includes not only the root layerStack, but all the layers reached by references/payloads (recursively) and layers that have been loaded for Value Clips.  Since SdfLayerTree is not a suitable representation for such a web of dependencies, we don't use it for public-facing data.

If you are only interested in the recursive sublayers of the root layer, you can have a look at usdview's [GetRootLayerStackInfo](https://github.com/PixarAnimationStudios/OpenUSD/blob/dev/pxr/usdImaging/usdviewq/common.py#L486), which reconstructs the root layer's nested sublayer hierarchy, including layers that have been muted on the stage (which GetUsedLayers will not include because they are not currently participating in the composition)

**Comment by adalast** [comment]
I will take a look at that function.  I need to get everything that the stage will be needing to render.  I may split it out into two methods, a fast one using GetUsedLayers() and a more detailed one that finds all of the layer files for variations and muted probably using GetRootLayerStackInfo as you have suggested.  The more ways I can have to get at the needed data the better as that means I can have flags for turning on and off methods which will add a lot of flexibility. The whole project is rather intense as I also have to reformat the data for use by the internal tool as well, so this will hopefully help.  

A very useful utility function would be one that would return either a tuple pair of (layer, filepath) or something to that effect for all of the files in the scene as well.  I have been digging and I have not found a good way to aggregate everything from within the format, so I am left borderline brute forcing it.

**Comment by spiffmon** [comment]
Please have a look at [UsdUtilsComputeAllDependencies()](https://openusd.org/dev/api/dependencies_8h.html#a074224fcf7c0ac30d4a218ba6d90e498).  It is the most complete dependencies analyzer we provide; it's the logic we use when creating a USDZ package that **must** contain everything that will be needed to render.

**Comment by adalast** [comment]
@spiffmon I saw that function and tried for an entire day to figure out how to get it to work, but I cannot seem to get the arguments correct.  Ideally I'd be able to call it on the root prim of the stage or on the stage itself, but the AssetPath argument seems to argue with me.  Also, using pxr.UsdUtils.ComputeAllDependencies() I'm not sure what variable type to use for the other three arguments that are being passed by reference.

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8969

**Comment by spiffmon** [comment]
@adalast , the `assetPath` argument is simply the path that your ArResolver can resolve to the **root layer** of the stage you wish to analyze.  It's not possible to restrict the analysis to a particular set of prims - it uses all information contained in the layer and the other layers it finds, recursively.

**Comment by adalast** [comment]
@spiffmon Sorry for the delay, with the holiday things got hectic.  I am trying to use the UsdUtils.ComputeAllDependencies() function, but I am still running up against issues.  Here is the function I am trying to get working:
```
def findAssetDependencies(stage: Usd.Stage):
    layers          = []
    assets          = [] 
    unresolvedPaths = []
    basePath        = stage.GetRootLayer()
    
    print(basePath)
    
    test = UsdUtils.ComputeAllDependencies(basePath, layers, assets, unresolvedPaths)
    print(test)
```

The basePath print yields this: `Sdf.Find('anon:000000000EA2A800:LOP:rootlayer')`

And I get this error on the code itself:
```
Python error: Traceback (most recent call last):
File "<stdin>", line 93, in <module>
File "<stdin>", line 20, in findAssetDependencies
Boost.Python.ArgumentError: Python argument types in
pxr.UsdUtils._usdUtils.ComputeAllDependencies(Layer, list, list, list)
did not match C++ signature:
ComputeAllDependencies(class pxrInternal_v0_22__pxrReserved__::SdfAssetPath assetPath)
```

I did attempt to remove the additional arguments and just use basePath and it still threw a very similar error.

**Comment by spiffmon** [comment]
The method requires an SdfAssetPath argument, and your `basePath` is an
SdfLayer. You can’t turn the identifier for an anonymous layer into a valid
AssetPath, because there is no asset, so it’s unfortunately not going to
work out. In theory we should be able to allow the specified root layer to
be anonymous, but that would not be viable for the adjacent (and shared)
asset localization functionality… and any other anonymous layer reached by
reference would be problematic as an asset dependency also.

It looks like you are in lop-land, where many layers are anonymous, so it
seems like you wouldn’t be able to use our utilities until after you have
exported.

**Comment by adalast** [comment]
@spiffmon Ok, so the traversal methods I already wrote are going to be the ones I have to use.  They seem to be complete in their traversal, was just hoping I could use the inbuilt ones.  It is weird that it is getting the anon layer though as it is pulling from a USDA file.  I tried to generate the SdfAssetPath from the path in the parameter on the LOP, but I was unable to figure out how to use the generator for it.

**Comment by spiffmon** [comment]
You might try the Houdini forums for the lops/layers question... though I
suspect that the usda file you open gets copied into an anon layer, and
that's what you have access to?

--spiff

**Comment by adalast** [comment]
When I use the UsdStage.GetUsedLayers() function I get the proper paths for everything, so I'm not sure what Houdini is doing under the hood with the layers for UsdStage.GetRootLayer().  Combining the UsdStage.GetUsedLayers() to grab the layer files with UsdStage.TraverseAll() to find any paths in attributes is hopefully going to be good enough.
