### ISSUE TITLE
Prim adapter error in usdrecord

### ISSUE THREAD

**Issue by anderslanglands** [PixarAnimationStudios/USD#2826]
### Description of Issue
usdrecord errors out with prim adapter errors

### Steps to Reproduce
1.  Build latest dev
2. run `usdrecord <some layer.usd> ./out.exr

Get the following:
```
Traceback (most recent call last):
  File "C:\Users\alanglands\code\OpenUSD-alanglands\dist\bin\usdrecord", line 223, in <module>
    sys.exit(main())
  File "C:\Users\alanglands\code\OpenUSD-alanglands\dist\bin\usdrecord", line 197, in main
    frameRecorder = UsdAppUtils.FrameRecorder(rendererPluginId, args.gpuEnabled, args.defaultLightDisabled)
pxr.Tf.ErrorException:
        Error in 'pxrInternal_v0_23__pxrReserved__::UsdImagingAdapterRegistry' at line 139 in file C:\Users\alanglands\code\OpenUSD-alanglands\pxr\usdImaging\usdImaging\adapterRegistry.cpp : '[PluginDiscover] A prim adapter for primType 'PxrBarnLightFilter' already exists! Overriding prim adapters at runtime is not supported. The last discovered adapter (UsdRiPxrImagingBarnLightFilterAdapter) will be used. The previously discovered adapter (UsdRiImagingPxrBarnLightFilterAdapter) will be discarded.'
        Error in 'pxrInternal_v0_23__pxrReserved__::UsdImagingAdapterRegistry' at line 139 in file C:\Users\alanglands\code\OpenUSD-alanglands\pxr\usdImaging\usdImaging\adapterRegistry.cpp : '[PluginDiscover] A prim adapter for primType 'PxrDisplayFilterPluginBase' already exists! Overriding prim adapters at runtime is not supported. The last discovered adapter (UsdRiImagingPxrDisplayFilterAdapter) will be used. The previously discovered adapter (UsdRiPxrImagingDisplayFilterAdapter) will be discarded.'
        Error in 'pxrInternal_v0_23__pxrReserved__::UsdImagingAdapterRegistry' at line 139 in file C:\Users\alanglands\code\OpenUSD-alanglands\pxr\usdImaging\usdImaging\adapterRegistry.cpp : '[PluginDiscover] A prim adapter for primType 'PxrIntMultLightFilter' already exists! Overriding prim adapters at runtime is not supported. The last discovered adapter (UsdRiImagingPxrIntMultLightFilterAdapter) will be used. The previously discovered adapter (UsdRiPxrImagingIntMultLightFilterAdapter) will be discarded.'
        Error in 'pxrInternal_v0_23__pxrReserved__::UsdImagingAdapterRegistry' at line 139 in file C:\Users\alanglands\code\OpenUSD-alanglands\pxr\usdImaging\usdImaging\adapterRegistry.cpp : '[PluginDiscover] A prim adapter for primType 'PxrSampleFilterPluginBase' already exists! Overriding prim adapters at runtime is not supported. The last discovered adapter (UsdRiImagingPxrSampleFilterAdapter) will be used. The previously discovered adapter (UsdRiPxrImagingSampleFilterAdapter) will be discarded.'
        Error in 'pxrInternal_v0_23__pxrReserved__::UsdImagingAdapterRegistry' at line 139 in file C:\Users\alanglands\code\OpenUSD-alanglands\pxr\usdImaging\usdImaging\adapterRegistry.cpp : '[PluginDiscover] A prim adapter for primType 'PxrRodLightFilter' already exists! Overriding prim adapters at runtime is not supported. The last discovered adapter (UsdRiImagingPxrRodLightFilterAdapter) will be used. The previously discovered adapter (UsdRiPxrImagingRodLightFilterAdapter) will be discarded.'
        Error in 'pxrInternal_v0_23__pxrReserved__::UsdImagingAdapterRegistry' at line 139 in file C:\Users\alanglands\code\OpenUSD-alanglands\pxr\usdImaging\usdImaging\adapterRegistry.cpp : '[PluginDiscover] A prim adapter for primType 'PxrIntegratorPluginBase' already exists! Overriding prim adapters at runtime is not supported. The last discovered adapter (UsdRiImagingPxrIntegratorAdapter) will be used. The previously discovered adapter (UsdRiPxrImagingIntegratorAdapter) will be discarded.'
```

### System Information (OS, Hardware)
Windows 11

### Build Flags
`cmake -B build -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_INSTALL_PREFIX=dist -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE="$env:Python3_EXECUTABLE" -DPXR_BUILD_TESTS=OFF -DPXR_BUILD_EMBREE_PLUGIN=TRUE -DEMBREE_LOCATION="$env:EMBREE_ROOT" -DPXR_BUILD_OPENIMAGEIO_PLUGIN=ON -DPXR_BUILD_DOCUMENTATION=ON`

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8981

**Comment by spiffmon** [comment]
@anderslanglands , there was a big renaming of alot of adapters and other plugins recently.  Can you ensure you have **completely** nuked your OpenUSD environment before attempting to build and install from dev or 23.11 ?

**Comment by anderslanglands** [comment]
Thanks Spiff, nuking everything and rebuilding from scratch did indeed fix it.
