### ISSUE TITLE
invalid plugin HdPrmanLoaderRendererPlugin in windows when trying to use prman renderer 

### ISSUE THREAD

**Issue by hyc0612** [PixarAnimationStudios/USD#2887]
### Description of Issue

dummped message:

Warning: in Load at line 112 of D:\Code\OpenUSD_hyc\pxr\imaging\plugin\hdPrmanLoader\rendererPlugin.cpp -- Could not load versioned hdPrman backend: The specified procedure could not be found.

Traceback (most recent call last):
  File "D:\install\USD_hyc\USD_monolithic_prman\lib\python\pxr\Usdviewq\appController.py", line 1453, in <lambda>
    self._rendererPluginChanged(pluginType))
  File "D:\install\USD_hyc\USD_monolithic_prman\lib\python\pxr\Usdviewq\appController.py", line 1414, in _rendererPluginChanged
    if not self._stageView.SetRendererPlugin(plugin):
  File "D:\install\USD_hyc\USD_monolithic_prman\lib\python\pxr\Usdviewq\stageView.py", line 988, in SetRendererPlugin
    if self._renderer.SetRendererPlugin(plugId):
pxr.Tf.ErrorException:
        Error in 'pxrInternal_v0_23__pxrReserved__::UsdImagingGLEngine::SetRendererPlugin' at line 969 in file D:\Code\OpenUSD_hyc\pxr\usdImaging\usdImagingGL\engine.cpp : 'Invalid plugin id or plugin is unsupported: HdPrmanLoaderRendererPlugin'

### Steps to Reproduce
1. `python D:/Code/OpenUSD_hyc/build_scripts/build_usd.py -v --build-variant release --build-monolithic --ptex --openimageio --alembic --materialx --embree --prman --prman-location "C:\Program Files\Pixar\RenderManProServer-25.2" "D:/install/USD_hyc/USD_monolithic_prman"`
here are the plugins built after build_usd.py
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/40915371/36aa8b98-6fbf-4351-aa2f-9d45e7bcf37b)

3. set path: 
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/40915371/770dd844-4dae-4565-868d-69da1ca5ce41)
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/40915371/c80c4730-4187-482c-a0fb-d1cb048ef3c3)
4. `usdview cube.usda` in commandline, and the error message showed up

here are the error windows popped out
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/40915371/4fe2a2ee-c0c2-46d3-9200-76397cee8df4)

translation:
Unable to locate program entry point StackWalk2 in DLL C:\Windows\SYSTEM32\dbgeng.dll

PS. I have confirmed that the dll exists for sure.

### System Information (OS, Hardware)
windows

### Package Versions
USD: 23.11

### Build Flags

python D:/Code/OpenUSD_hyc/build_scripts/build_usd.py -v --build-variant release --build-monolithic --ptex --openimageio --alembic --materialx --embree --prman --prman-location "C:\Program Files\Pixar\RenderManProServer-25.2" "D:/install/USD_hyc/USD_monolithic_prman"

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-9118

**Comment by spiffmon** [comment]
Hello, @hyc0612, would it be possible for you to try a non-monolithic build and see if you experience the same problem?

**Comment by hyc0612** [comment]
Unfortunately, I 've tried but encountered the same issue

F. Sebastian (spiff) Grassia ***@***.***> 于2024年2月3日周六
05:16写道：

**Comment by sunyab** [comment]
Could you try adding `D:\install\USD_hyc\USD_monolithic_prman\plugin\usd` to your PATH and seeing if that helps?

**Comment by hyc0612** [comment]
> Could you try adding `D:\install\USD_hyc\USD_monolithic_prman\plugin\usd` to your PATH and seeing if that helps?

![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/40915371/2bb44a56-ec56-437b-bb1a-d0af2850c60c)
