### ISSUE TITLE
python pxr import crash under almalinux 9.3

### ISSUE THREAD

**Issue by fjallraven** [PixarAnimationStudios/USD#2986]
### Description of Issue

I've built vfx platform 2023 on almalinux 9.3,

Tested complete build with `_GLIBCXX_USE_CXX11_ABI` unset and `_GLIBCXX_USE_CXX11_ABI=1`

Tested both USD 24.03 and 23.11, same error issue

When trying to import the python pxr library it fails with the following stack trace.

Any ideas what might be going on?

python 3.10.12:
```
> from pxr ipmort Usd
free(): invalid pointer
```

```
gef➤  bt
#0  0x00007f56a7ea154c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007f56a7e54d06 in raise () from /lib64/libc.so.6
#2  0x00007f56a7e287f3 in abort () from /lib64/libc.so.6
#3  0x00007f56a7e29130 in __libc_message.cold () from /lib64/libc.so.6
#4  0x00007f56a7eab617 in malloc_printerr () from /lib64/libc.so.6
#5  0x00007f56a7eacecc in _int_free () from /lib64/libc.so.6
#6  0x00007f56a7eaf955 in free () from /lib64/libc.so.6
#7  0x00007f5699817cb7 in std::default_delete<char []>::operator()<char> (this=0x7ffde52a1970, __ptr=0x7f569880d000 "/dev/vfx_platform_2023/python3.10/3.10/bin/python3.10") at /dev/vfx_platform_2023/gcc/11.2.0/include/c++/11.2.0/bits/unique_ptr.h:120
#8  0x00007f569985f9d8 in std::unique_ptr<char, std::default_delete<char []> >::~unique_ptr (this=0x7ffde52a1970, __in_chrg=<optimized out>) at /dev/vfx_platform_2023/gcc/11.2.0/include/c++/11.2.0/bits/unique_ptr.h:361
#9  0x00007f569a4d3744 in pxrInternal_v0_24__pxrReserved__::(anonymous namespace)::_DynamicSizedRead(size_t, const std::function<bool(char*, long unsigned int*)> &) (initialSize=0x1000, callback=...) at /dev/vfx_platform_2023_build/OpenUSD-24.03/pxr/base/arch/systemInfo.cpp:109
#10 0x00007f569a4d38bc in pxrInternal_v0_24__pxrReserved__::ArchGetExecutablePath[abi:cxx11]() () at /dev/vfx_platform_2023_build/OpenUSD-24.03/pxr/base/arch/systemInfo.cpp:146
#11 0x00007f569a4d64f1 in pxrInternal_v0_24__pxrReserved__::(anonymous namespace)::Arch_InitConfig () at /dev/vfx_platform_2023_build/OpenUSD-24.03/pxr/base/arch/initConfig.cpp:52
#12 0x00007f56a8bcf1ae in call_init (env=0x7ffde52a68f0, argv=0x7ffde52a68d8, argc=0x2, l=<optimized out>) at dl-init.c:70
#13 call_init (l=<optimized out>, argc=0x2, argv=0x7ffde52a68d8, env=0x7ffde52a68f0) at dl-init.c:26
#14 0x00007f56a8bcf29c in _dl_init (main_map=0x1231bd0, argc=0x2, argv=0x7ffde52a68d8, env=0x7ffde52a68f0) at dl-init.c:117
#15 0x00007f56a7f95e15 in _dl_catch_exception () from /lib64/libc.so.6
#16 0x00007f56a8bd5c8e in dl_open_worker
#17 0x00007f56a7f95db8 in _dl_catch_exception () from /lib64/libc.so
#18 0x00007f56a8bd601f in _dl_open (file=<optimized out>, mode=0x80000002, caller_dlopen=0x7f56a89e17ff <_PyImport_FindSharedFuncptr+303>, nsid=0xfffffffffffffffe, argc=0x2, argv=0x7ffde52a68d8, env=0x7ffde52a68f0) at dl-open.c:879
#19 0x00007f56a7e9b86c in dlopen_doit () from /lib64/libc.so.6
#20 0x00007f56a7f95db8 in _dl_catch_exception () from /lib64/libc.so.6
#21 0x00007f56a7f95e83 in _dl_catch_error () from /lib64/libc.so.6
#22 0x00007f56a7e9b33e in _dlerror_run () from /lib64/libc.so.6
#23 0x00007f56a7e9b921 in dlopen@GLIBC_2.2.5 () from /lib64/libc.so.6
#24 0x00007f56a89e17ff in _PyImport_FindSharedFuncptr (prefix=<optimized out>, shortname=0x7f569a6a5e20 "_tf", pathname=0x7f569a60b390 "/dev/vfx_platform_2023/usd/24.03/lib/python/pxr/Tf/_tf.so", fp=0x0) at ./Python/dynload_shlib.c:100
#25 0x00007f56a89affed in _PyImport_LoadDynamicModuleWithSpec (spec=0x7f569a533250, fp=0x0) at ./Python/importdl.c:137
#26 0x00007f56a89af97d in _imp_create_dynamic_impl (spec=0x7f569a533250, file=<optimized out>, module=<optimized out>) at Python/import.c:2050
```

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9384

**Comment by FlorianZ** [comment]
Hi @fjallraven. We had a look at the crashing code and we think it's worth for us taking a look. However, we aren't currently running into this, and won't have the opportunity to test with Python 3.10 until we are switching to VFX reference platform CY2023 or later. Do you think this could be Python 3.10 related? Any chance you can try with 3.9? Thank you!
