### ISSUE TITLE
Usdview no renderer

### ISSUE THREAD

**Issue by jhultgre** [PixarAnimationStudios/USD#3109]
### Description of Issue
I compiled usd successfully but when I try to launch usd view the viewport is black and it throws this error over and over again.
```
Traceback (most recent call last):
  File "z:\techart\python\3.10\usd\out\lib\python\pxr\Usdviewq\stageView.py", line 1646, in paintGL
    renderer = self._getRenderer()
  File "z:\techart\python\3.10\usd\out\lib\python\pxr\Usdviewq\stageView.py", line 959, in _getRenderer
    self._renderer = UsdImagingGL.Engine(params)
pxr.Tf.ErrorException:
        Error in 'pxrInternal_v0_24__pxrReserved__::HdRendererPluginRegistry::CreateRenderDelegate' at line 100 in file Z:\techart\python\3.10\usd\USD\pxr\imaging\hd\rendererPluginRegistry.cpp : 'Couldn't find plugin for id '
        Error in 'pxrInternal_v0_24__pxrReserved__::UsdImagingGLEngine' at line 205 in file Z:\techart\python\3.10\usd\USD\pxr\usdImaging\usdImagingGL\engine.cpp : 'No renderer plugins found!'
```

### System Information (OS, Hardware)
Windows 10

### Package Versions
python 3.10.8
pyside2

**Comment by jhultgre** [comment]
I think this was my fault trying to delete unneeded files after the build finished.
