### ISSUE TITLE
Launching USD view with Prman and crashing

### ISSUE THREAD

**Issue by LaurentGarcia** [PixarAnimationStudios/USD#3210]
### Description of Issue
❯ usdview --renderer Prman /Users/lgarcia/Code/repositories/caldera/map_source/prefabs/br/wz_vg/mp_wz_island/commercial/hotel_01.usd

usdview --renderer Prman /Users/lgarcia/Code/repositories/caldera/map_source/prefabs/br/wz_vg/mp_wz_island/commercial/hotel_01.usd
2024-08-06 21:57:54.833 python[29915:4195471] +[IMKClient subclass]: chose IMKClient_Legacy
Traceback (most recent call last):
  File "/Users/lgarcia/Code/repositories/OpenUSD/INSTALL/bin/usdview", line 18, in <module>
    Usdviewq.Launcher().Run()
  File "/Users/lgarcia/Code/repositories/OpenUSD/INSTALL/lib/python/pxr/Usdviewq/__init__.py", line 69, in Run
    app, appController = self.LaunchPreamble(arg_parse_result)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lgarcia/Code/repositories/OpenUSD/INSTALL/lib/python/pxr/Usdviewq/__init__.py", line 383, in LaunchPreamble
    appController = AppController(arg_parse_result, contextCreator)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lgarcia/Code/repositories/OpenUSD/INSTALL/lib/python/pxr/Usdviewq/appController.py", line 1133, in __init__
    self._drawFirstImage()
  File "/Users/lgarcia/Code/repositories/OpenUSD/INSTALL/lib/python/pxr/Usdviewq/appController.py", line 1145, in _drawFirstImage
    QtWidgets.QApplication.processEvents()
  File "/Users/lgarcia/Code/repositories/OpenUSD/INSTALL/lib/python/pxr/Usdviewq/stageView.py", line 1638, in paintGL
    renderer = self._getRenderer()
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/lgarcia/Code/repositories/OpenUSD/INSTALL/lib/python/pxr/Usdviewq/stageView.py", line 951, in _getRenderer
    self._renderer = UsdImagingGL.Engine(params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
pxr.Tf.ErrorException:
	Error in 'pxrInternal_v0_24__pxrReserved__::UsdImagingGLEngine::SetRendererPlugin' at line 1005 in file /Users/lgarcia/Code/repositories/OpenUSD/pxr/usdImaging/usdImagingGL/engine.cpp : 'Invalid plugin id or plugin is unsupported: HdPrmanLoaderRendererPlugin'
	Error in 'pxrInternal_v0_24__pxrReserved__::UsdImagingGLEngine' at line 188 in file /Users/lgarcia/Code/repositories/OpenUSD/pxr/usdImaging/usdImagingGL/engine.cpp : 'No renderer plugins found!'

### Steps to Reproduce
1. ❯ usdview --renderer Prman /Users/lgarcia/Code/repositories/caldera/map_source/prefabs/br/wz_vg/mp_wz_island/commercial/hotel_01.usd 

### System Information (OS, Hardware)

MacOs 15.0, MacBook Pro 15 arm

### Build Flags
❯ python ./build_scripts/build_usd.py --prman --prman-location=$RMANTREE  ./INSTALL

My env Variables looks like:

export PYTHONPATH=/Users/lgarcia/Code/repositories/OpenUSD/INSTALL/lib/python:$PYTHONPATH
export PATH=/Users/lgarcia/Code/repositories/OpenUSD/INSTALL/bin:$PATH
export USD_INSTALL_ROOT=/Users/lgarcia/Code/repositories/OpenUSD/INSTALL

# RenderMan environment variables
export RMANTREE=/Applications/Pixar/RenderManProServer-26.1
export RMAN_SHADERPATH=$RMANTREE/lib/shaders:$USD_INSTALL_ROOT/plugin/usd/usdShaders/
export RMAN_RIXPLUGINPATH=$RMANTREE/lib/plugins
export RMAN_TEXTUREPATH=$RMANTREE/lib/textures:$RMANTREE/lib/plugins:$USD_INSTALL_ROOT/plugin/usd

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9947
