### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by usman317319** [PixarAnimationStudios/USD#3250]
### Description of Issue
Getting this error while trying to execute usdview command

Fatal Python error: could not init enum
Python runtime state: initialized
Traceback (most recent call last):
  File "shibokensupport/signature/loader.py", line 54, in feature_import
  File "shibokensupport/feature.py", line 89, in feature_import
RecursionError: maximum recursion depth exceeded while calling a Python object

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, xxsubtype, shiboken6.Shiboken, PySide6.QtCore (total: 16)
Aborted (core dumped)

### System Information (OS, Hardware)
Ubuntu Linux

**Comment by jesschimein** [comment]
Filed as internal issue #USD-10029
