### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by brothermechanic** [PixarAnimationStudios/USD#3349]
### Description of Issue
I build openusd without issues. But when i run, for ex, usdview - i get 
```
$ usdview
Traceback (most recent call last):
  File "/usr/lib64/openusd/.bin/usdview", line 11, in <module>
    import pxr.Usdviewq as Usdviewq
  File "/usr/lib/python3.12/site-packages/pxr/Usdviewq/__init__.py", line 10, in <module>
    from pxr import Tf
  File "/usr/lib/python3.12/site-packages/pxr/Tf/__init__.py", line 161, in <module>
    PreparePythonModule()
  File "/usr/lib/python3.12/site-packages/pxr/Tf/__init__.py", line 86, in PreparePythonModule
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /usr/lib64/openusd/lib/libusd_ms.so: undefined symbol: _ZTVN16OpenImageIO_v2_510Filesystem11IOMemReaderE

```

### System Information (OS, Hardware)
i7-11700K, RTX-3800
Gentoo Linux, Gentoo 13.3.1_p20240614 p17, Python 3.12.6, glibc-2.39-r6, llvm-18
### Package Versions
openusd-24.08
### Build Flags
https://github.com/brothermechanic/cg/blob/master/media-libs/openusd/openusd-24.08.ebuild

Help me to find, where is a problem?

**Comment by jesschimein** [comment]
Filed as internal issue #USD-10254

**Comment by brothermechanic** [comment]
@jesschimein Thank you for answer! So, it will be fixed soon? Hope)

**Comment by jesschimein** [comment]
Hi!  The internal issue comment means the information has been [copied into our internal issue tracker ](https://openusd.org/dev/contributing_to_usd.html#github-issues). Unfortunately, it doesn't mean the issue has been triaged yet.  

If you're looking for help more urgently, I'd recommend posting in the [AOUSD forum](https://forum.aousd.org/)!  We have a great community and someone might have an answer to your question.

**Comment by dgovil** [comment]
Can you build with Python 3.11? USD/Boost doesn't support 3.12 fully yet.
