### ISSUE TITLE
usdview fails after "file > reopen"

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#730]
### Description of Issue
Title says it all, I get this error:

Traceback (most recent call last):
  File "C:\src\usd\_build-monolithic-py\lib\python\pxr\Usdviewq\stageView.py", line 1665, in paintGL
    self.DrawCameraGuides(viewProjectionMatrix)
  File "C:\src\usd\_build-monolithic-py\lib\python\pxr\Usdviewq\stageView.py", line 1085, in DrawCameraGuides
    for camera in self._allSceneCameras:
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\src\usd\_build-monolithic-py\lib\python\pxr\Usdviewq\stageView.py", line 1517, in paintGL
    GL.glEnable(GL_FRAMEBUFFER_SRGB_EXT)
  File "C:\python27_amd64\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = 'invalid operation',
        baseOperation = glEnable,
        cArguments = (GL_FRAMEBUFFER_SRGB_EXT,)
)

### Steps to Reproduce
1. Open a usd file
2. Hit file > reopen stage

### System Information (OS, Hardware)
Windows

### Package Versions
18.11

### Build Flags
--build-monolithic --openimageio

**Comment by superfunc** [comment]
I saw this when messing around with my recent PR #717 .

**Comment by jtran56** [comment]
Filed as internal issue #USD-4993.
