### ISSUE TITLE
Getting GLError when openning usdview

### ISSUE THREAD

**Issue by ebargoogle** [PixarAnimationStudios/USD#746]
When I try to open any usd file with usdview, I get this error:

Traceback (most recent call last):
  File "C:\Users\ebar\Documents\USD2\lib\python\pxr\Usdviewq\stageView.py", line 2131, in glDraw
    if not self._getRenderer():
  File "C:\Users\ebar\Documents\USD2\lib\python\pxr\Usdviewq\stageView.py", line 907, in _getRenderer
    self._handleRendererChanged(self.GetCurrentRendererId())
  File "C:\Users\ebar\Documents\USD2\lib\python\pxr\Usdviewq\stageView.py", line 914, in _handleRendererChanged
    self._rendererDisplayName = self.GetRendererDisplayName(rendererId)
  File "C:\Users\ebar\Documents\USD2\lib\python\pxr\Usdviewq\stageView.py", line 932, in GetRendererDisplayName
    return self._renderer.GetRendererDisplayName(plugId)
pxr.Tf.ErrorException:
        Error in 'pxrInternal_v0_19__pxrReserved__::UsdImagingGLEngine::GetRendererDisplayName' at line 654 in file C:\Users\ebar\Downloads\USD-master\pxr\usdImaging\lib\usdImagingGL\engine.cpp : 'Failed verification: ' HdxRendererPluginRegistry::GetInstance(). GetPluginDesc(id, &pluginDescriptor) ''
Traceback (most recent call last):
  File "C:\Users\ebar\Documents\USD2\lib\python\pxr\Usdviewq\stageView.py", line 1547, in paintGL
    GL.glEnable(GL_FRAMEBUFFER_SRGB_EXT)
  File "C:\Python27\lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "C:\Python27\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1280,
        description = 'invalid enumerant',
        baseOperation = glEnable,
        cArguments = (GL_FRAMEBUFFER_SRGB_EXT,)
)
Traceback (most recent call last):
  File "C:\Users\ebar\Documents\USD2\lib\python\pxr\Usdviewq\stageView.py", line 1547, in paintGL
    GL.glEnable(GL_FRAMEBUFFER_SRGB_EXT)
  File "C:\Python27\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1280,
        description = 'invalid enumerant',
        baseOperation = glEnable,
        cArguments = (GL_FRAMEBUFFER_SRGB_EXT,)
)

I even reoistalled USD and that didn't make a difference. Also it was working just fine a few days ago, not sure what caused the issue.

PySide version:1.2.4
PyOpenGl version:3.1.0
OS: Windows 10
branch: master

**Comment by ebargoogle** [comment]
Quick update, I cloned the repo again and reinstalled and the issue is gone!
