### ISSUE TITLE
Hd: Bad topology results in confusing output

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#92]
I accidentally specified too many triangles in a usd file and got this error message from usdview:

The first warning is great:

Warning: in Hd_TriangleIndexBuilderComputation::Resolve at line 187 of C:\src\usd\USD.jcowles\pxr\imaging\lib\hd\triangulate.cpp -- **numVerts and verts are incosistent** [/Head]

but the next ones are just confusing and actually hide the good warning (also would be nice if errors could be more concise / readable):

Warning: in HdResourceRegistry::Commit at line 400 of C:\src\usd\USD.jcowles\pxr\imaging\lib\hd\resourceRegistry.cpp -- **Too many iterations in resolving buffer source. It's likely due to incosistent dependency.**
Traceback (most recent call last):
  File "C:\src\usd\stage\local\lib\python\pxr\Usdviewq\stageView.py", line 1744, in paintGL
    self.drawSelHighlights)
  File "C:\src\usd\stage\local\lib\python\pxr\Usdviewq\stageView.py", line 1473, in renderSinglePass
    self._renderer.Render(pseudoRoot, self._renderParams)

pxr.Tf.ErrorException:
        Error in 'Hd_AdjacencyBuilderComputation::Resolve' at line 236 in file C:\src\usd\USD.jcowles\pxr\imaging\lib\hd\vertexAdjacency.cpp : 'vertex index out of range index: -363441607 numPoints: 3592'
        Error in 'HdResourceRegistry::Commit' at line 405 in file C:\src\usd\USD.jcowles\pxr\imaging\lib\hd\resourceRegistry.cpp : 'Failed verification: ' numBufferSourcesResolved == _numBufferSourcesToResolve ''
        Error in 'HdVBOMemoryManager::_StripedBufferArrayRange::CopyData' at line 517 in file C:\src\usd\USD.jcowles\pxr\imaging\lib\hd\vboMemoryManager.cpp : 'Failed verification: ' bufferSource->GetNumComponents() == VBO->GetNumComponents() ' -- packedNormals: 0 != 1
'

**Comment by takahito-tejima** [comment]
Thanks for filing Jeremy. We are (slowly) adding more validations and graceful fallback in Hd. I'll take care of this case too.

**Comment by jcowles** [comment]
Cool!

I also realized non-renderman people probably have no idea what "numverts" and "verts" means -- a message that either matches USD terminology or just "inconsistent topology and points" would be more clear.

Thanks Takahito!

**Comment by jtran56** [comment]
Filed as internal issue #139319.
