### ISSUE TITLE
Error on launching usdview on mac and Linux

### ISSUE THREAD

**Issue by ebargoogle** [PixarAnimationStudios/USD#923]
### Description of Issue

When I try to launch usdview after a fresh USD install, I get this error:

Traceback (most recent call last):
  File "/opt/local/USD/bin/usdview", line 32, in <module>
    Usdviewq.Launcher().Run()
  File "/opt/local/USD/lib/python/pxr/Usdviewq/__init__.py", line 67, in Run
    self.__LaunchProcess(arg_parse_result)
  File "/opt/local/USD/lib/python/pxr/Usdviewq/__init__.py", line 290, in __LaunchProcess
    (app, appController) = self.LaunchPreamble(arg_parse_result)
  File "/opt/local/USD/lib/python/pxr/Usdviewq/__init__.py", line 280, in LaunchPreamble
    appController = AppController(arg_parse_result, contextCreator)
  File "/opt/local/USD/lib/python/pxr/Usdviewq/appController.py", line 356, in __init__
    self._ui.setupUi(self._mainWindow)
  File "/opt/local/USD/lib/python/pxr/Usdviewq/mainWindowUI.py", line 1045, in setupUi
    self.retranslateUi(MainWindow)
  File "/opt/local/USD/lib/python/pxr/Usdviewq/mainWindowUI.py", line 1094, in retranslateUi
    self.metadataView.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "Field Name", None, -1))
AttributeError: 'NoneType' object has no attribute 'setText'

### Steps to Reproduce
1. Install fresh USD on mac
2. Try usdview

### System Information (OS, Hardware)
Mac OS

**Comment by ebargoogle** [comment]
Just installed usd on a new linux mchine and got the same error.

**Comment by spiffmon** [comment]
Please see https://github.com/PixarAnimationStudios/USD/issues/914
