### ISSUE TITLE
Boost::shared_ptr crashes when opening a scene in usdview using gcc 5.4

### ISSUE THREAD

**Issue by sirpalee** [PixarAnimationStudios/USD#94]
### System Information (OS, Hardware, etc.)
OS: Ubuntu 16.04 LTS, Intel Xeon X5675 and Quadro K4200.

### Package Versions (Only listing the relevant ones)
USD: 3f759efc05568a6a04e36aedc6154a8610afb650 with PR #55 applied on top.
gcc: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
cmake: 3.5.1
boost: 1.58
tbb: 2015.09.R2-1

### Build Flags
Just setting up deps, and setting the build mode to debug.
    
### Steps to Reproduce
1. Build USD in debug mode.
2. Open the following usda file with usdview.
```
#usda 1.0

def Xform "hello"
{
    def Sphere "world"
    {
    }
}
```

The steps lead to the following stack trace.

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffeaffe6a9 in boost::detail::atomic_increment (pw=0x49)
    at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:66
66	    );
(gdb) bt
#0  0x00007fffeaffe6a9 in boost::detail::atomic_increment (pw=0x49)
    at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:66
#1  0x00007fffeaffe78a in boost::detail::sp_counted_base::add_ref_copy (
    this=0x41)
    at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:134
#2  0x00007fffeaffe89f in boost::detail::shared_count::shared_count (
    this=0x7fffffffb120, r=...)
    at /usr/include/boost/smart_ptr/detail/shared_count.hpp:454
#3  0x00007fffe7234c19 in boost::shared_ptr<ArResolverContext::_Untyped>::shared_ptr (this=0x7fffffffb118, r=...)
    at /usr/include/boost/smart_ptr/shared_ptr.hpp:392
#4  0x00007fffe7234b31 in ArResolverContext::ArResolverContext (
    this=0x7fffffffb118)
    at /home/palm/repos/build/usd-debug/include/pxr/usd/ar/resolverContext.h:84
#5  0x00007fffe72346b7 in ArResolverContextBinder::ArResolverContextBinder (
    this=0x7fffffffb110, resolver=0x2375d60, context=...)
    at /home/palm/repos/USD/pxr/usd/lib/ar/resolverContextBinder.cpp:32
#6  0x00007fff9858632f in PcpComputePrimIndex (primPath=..., layerStack=..., 
    inputs=..., outputs=0x7fffee6c6500, resolver=0x2375d60)
    at /home/palm/repos/USD/pxr/usd/lib/pcp/primIndex.cpp:4111
#7  0x00007fff984e1394 in Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>::_ComputeIndex (this=0x7fffffffb850, parentIndex=0x0, path=..., 
    checkCache=true) at /home/palm/repos/USD/pxr/usd/lib/pcp/cache.cpp:2290
#8  0x00007fff984f985f in std::_Mem_fn_base<void (Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>::*)(PcpPrimIndex const*, SdfPath, bool), true>::operator()<PcpPrimIndex const*&, SdfPath&, bool&, void> (
    this=0x7fffee6c6948, __object=0x7fffffffb850)
    at /usr/include/c++/5/functional:600
#9  0x00007fff984f60b1 in std::_Bind<std::_Mem_fn<void (Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>::*)(PcpPrimIndex const*, SdfPath, bool)> (Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>*, PcpPrimIndex const*, SdfPath, bool)>::__call<void, , 0ul, 1ul, 2ul, 3ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) (this=0x7fffee6c6948, 
    __args=<unknown type in /home/palm/dist/usd/lib/python/pxr/Usd/../../../libpcp.so, CU 0x22e962, DIE 0x3285dc>) at /usr/include/c++/5/functional:1074
#10 0x00007fff984f1db5 in std::_Bind<std::_Mem_fn<void (Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>::*)(PcpPrimIndex const*, SdfPath, bool)> (Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>*, PcpPrimIndex const*, SdfPath, bool)>::operator()<, void>() (this=0x7fffee6c6948)
    at /usr/include/c++/5/functional:1133
#11 0x00007fff984fd5be in WorkDispatcher::_InvokerTask<std::_Bind<std::_Mem_fn<void (Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>::*)(PcpPrimIndex const*, SdfPath, bool)> (Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>*, PcpPrimIndex const*, SdfPath, bool)> >::execute() (
    this=0x7fffee6c6940)
    at /home/palm/repos/build/usd-debug/include/pxr/base/work/dispatcher.h:145
#12 0x00007fffeed7bfdd in ?? () from /usr/lib/x86_64-linux-gnu/libtbb.so.2
#13 0x00007fffef8a72d7 in tbb::task::wait_for_all (this=0x7fffee6c6a40)
    at /usr/include/tbb/task.h:747
#14 0x00007fffef8a67e4 in WorkDispatcher::Wait (this=0x7fffffffb9a8)
    at /home/palm/repos/USD/pxr/base/lib/work/dispatcher.cpp:49
#15 0x00007fff984d953b in Pcp_ParallelIndexer<PcpCache::_UntypedIndexingChildrenPredicate>::RunAndWait (this=0x7fffffffb850)
    at /home/palm/repos/USD/pxr/usd/lib/pcp/cache.cpp:2245
#16 0x00007fff984c9f89 in PcpCache::_ComputePrimIndexesInParallel (
    this=0x237a4e0, roots=std::vector of length 1, capacity 1 = {...}, 
    allErrors=0x7fffffffbc50, childrenPred=..., payloadPred=..., 
    mallocTag1=0x7fff995d93a4 "Usd", 
    mallocTag2=0x7fff995d9258 "UsdStages in aggregate")
    at /home/palm/repos/USD/pxr/usd/lib/pcp/cache.cpp:2483
#17 0x00007fff994fc114 in PcpCache::ComputePrimIndexesInParallel<(anonymous namespace)::_NameChildrenPred, UsdStage::_ComposePrimIndexesInParallel(const std::vector<SdfPath>&, UsdStage::_IncludePayloadsRule, const string&, Usd_InstanceChanges*)::<lambda(const SdfPath&)> >(const SdfPathVector &, PcpErrorVector *, const (anonymous namespace)::_NameChildrenPred &, const UsdStage::<lambda(const SdfPath&)> &, const char *, const char *) (this=0x237a4e0, 
---Type <return> to continue, or q <return> to quit---
    paths=std::vector of length 1, capacity 1 = {...}, 
    allErrors=0x7fffffffbc50, childrenPred=..., payloadPred=..., 
    mallocTag1=0x7fff995d93a4 "Usd", 
    mallocTag2=0x7fff995d9258 "UsdStages in aggregate")
    at /home/palm/repos/build/usd-debug/include/pxr/usd/pcp/cache.h:326
#18 0x00007fff994f1fff in UsdStage::_ComposePrimIndexesInParallel (
    this=0x237a270, 
    primIndexPaths=std::vector of length 1, capacity 1 = {...}, 
    includeRule=UsdStage::_IncludeAllDiscoveredPayloads, 
    context="Instantiating stage", instanceChanges=0x0)
    at /home/palm/repos/USD/pxr/usd/lib/usd/stage.cpp:3376
#19 0x00007fff994e42cd in UsdStage::_InstantiateStage (rootLayer=..., 
    sessionLayer=..., pathResolverContext=..., load=UsdStage::LoadAll)
    at /home/palm/repos/USD/pxr/usd/lib/usd/stage.cpp:526
#20 0x00007fff995151ef in Usd_StageOpenRequest::Manufacture (
    this=0x7fffffffc0b0) at /home/palm/repos/USD/pxr/usd/lib/usd/stage.cpp:774
#21 0x00007fff9951f989 in UsdStage::_OpenImpl<TfWeakPtr<SdfLayer>, ArResolverContext> (load=UsdStage::LoadAll)
    at /home/palm/repos/USD/pxr/usd/lib/usd/stage.cpp:802
#22 0x00007fff994e60de in UsdStage::Open (rootLayer=..., 
    pathResolverContext=..., load=UsdStage::LoadAll)
    at /home/palm/repos/USD/pxr/usd/lib/usd/stage.cpp:875
#23 0x00007fff994e5af0 in UsdStage::Open (
    filePath="/home/palm/data/usd/sphere.usda", pathResolverContext=..., 
    load=UsdStage::LoadAll)
    at /home/palm/repos/USD/pxr/usd/lib/usd/stage.cpp:713
#24 0x00007fff9a074cff in boost::python::detail::invoke<Tf_MakePyConstructor::_RefPtrFactoryConverter<TfWeakPtr<UsdStage>, TfRefPtr<UsdStage> >, TfRefPtr<UsdStage> (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ArResolverContext const&, UsdStage::InitialLoadSet), boost::python::arg_from_python<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, boost::python::arg_from_python<ArResolverContext const&>, boost::python::arg_from_python<UsdStage::InitialLoadSet> > (rc=..., 
    f=@0x1c60cf8: 0x7fff994e592c <UsdStage::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ArResolverContext const&, UsdStage::InitialLoadSet)>, ac0=..., ac1=..., ac2=...)
    at /usr/include/boost/python/detail/invoke.hpp:75
#25 0x00007fff9a06d762 in boost::python::detail::caller_arity<3u>::impl<TfRefPtr<UsdStage> (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ArResolverContext const&, UsdStage::InitialLoadSet), boost::python::return_value_policy<TfPyRefPtrFactory<void>, boost::python::default_call_policies>, boost::mpl::vector4<TfRefPtr<UsdStage>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ArResolverContext const&, UsdStage::InitialLoadSet> >::operator() (this=0x1c60cf8, 
    args_=0x7fffcc03a320) at /usr/include/boost/python/detail/caller.hpp:223
#26 0x00007fff9a06688f in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<TfRefPtr<UsdStage> (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ArResolverContext const&, UsdStage::InitialLoadSet), boost::python::return_value_policy<TfPyRefPtrFactory<void>, boost::python::default_call_policies>, boost::mpl::vector4<TfRefPtr<UsdStage>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ArResolverContext const&, UsdStage::InitialLoadSet> > >::operator() (this=0x1c60cf0, args=0x7fffcc03a320, kw=0x7fffcc05aa28)
    at /usr/include/boost/python/object/py_function.hpp:38
#27 0x00007fffeefbb5cd in boost::python::objects::function::call(_object*, _object*) const () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
#28 0x00007fffeefbb7c8 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
#29 0x00007fffeefc3613 in boost::python::handle_exception_impl(boost::function0<void>) () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
#30 0x00007fffeefb8999 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
#31 0x00000000004b0de3 in PyObject_Call ()
#32 0x00007fffef545261 in Tf_ModuleProcessor::_InvokeWithErrorHandling (
    fn=..., funcName="pxr.Usd.Stage.Open", fileName="pxr.Usd.Stage", 
    funcLine=0, args=..., kw=...)
---Type <return> to continue, or q <return> to quit---
    at /home/palm/repos/USD/pxr/base/lib/tf/pyModule.cpp:168
#33 0x00007fffef54da99 in boost::_bi::list6<boost::_bi::value<boost::python::api::object>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<int>, boost::arg<1>, boost::arg<2> >::operator()<boost::python::handle<_object>, boost::python::handle<_object> (*)(boost::python::api::object const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, boost::python::tuple const&, boost::python::dict const&), boost::_bi::list2<boost::python::tuple const&, boost::python::dict const&> > (this=0x1c844c0, 
    f=@0x1c844b8: 0x7fffef54516e <Tf_ModuleProcessor::_InvokeWithErrorHandling(boost::python::api::object const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, boost::python::tuple const&, boost::python::dict const&)>, a=...)
    at /usr/include/boost/bind/bind.hpp:586
#34 0x00007fffef54d77c in boost::_bi::bind_t<boost::python::handle<_object>, boost::python::handle<_object> (*)(boost::python::api::object const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, boost::python::tuple const&, boost::python::dict const&), boost::_bi::list6<boost::_bi::value<boost::python::api::object>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<int>, boost::arg<1>, boost::arg<2> > >::operator()<boost::python::tuple, boost::python::dict>(boost::python::tuple&&, boost::python::dict&&) (this=0x1c844b8, 
    a1=<unknown type in /home/palm/dist/usd/lib/python/pxr/Work/../../../libtf.so, CU 0x3a3927, DIE 0x3d5c2c>, 
    a2=<unknown type in /home/palm/dist/usd/lib/python/pxr/Work/../../../libtf.so, CU 0x3a3927, DIE 0x3d5c31>) at /usr/include/boost/bind/bind.hpp:917
#35 0x00007fffef54d3aa in boost::python::detail::invoke<boost::python::to_python_value<boost::python::handle<_object> const&>, boost::_bi::bind_t<boost::python::handle<_object>, boost::python::handle<_object> (*)(boost::python::api::object const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, boost::python::tuple const&, boost::python::dict const&), boost::_bi::list6<boost::_bi::value<boost::python::api::object>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<int>, boost::arg<1>, boost::arg<2> > >, boost::python::arg_from_python<boost::python::tuple>, boost::python::arg_from_python<boost::python::dict> > (rc=..., f=..., ac0=..., ac1=...)
    at /usr/include/boost/python/detail/invoke.hpp:75
#36 0x00007fffef54cf8b in boost::python::detail::caller_arity<2u>::impl<boost::_bi::bind_t<boost::python::handle<_object>, boost::python::handle<_object> (*)(boost::python::api::object const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, boost::python::tuple const&, boost::python::dict const&), boost::_bi::list6<boost::_bi::value<boost::python::api::object>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<int>, boost::arg<1>, boost::arg<2> > >, boost::python::default_call_policies, boost::mpl::vector<boost::python::handle<_object>, boost::python::tuple, boost::python::dict, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na> >::operator() (this=0x1c844b8, args_=0x7fffefcc1320)
    at /usr/include/boost/python/detail/caller.hpp:223
#37 0x00007fffef54cd95 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<boost::_bi::bind_t<boost::python::handle<_object>, boost::python::handle<_object> (*)(boost::python::api::object const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, boost::python::tuple const&, boost::python::dict const&), boost::_bi::list---Type <return> to continue, or q <return> to quit---
6<boost::_bi::value<boost::python::api::object>, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::_bi::value<int>, boost::arg<1>, boost::arg<2> > >, boost::python::default_call_policies, boost::mpl::vector<boost::python::handle<_object>, boost::python::tuple, boost::python::dict, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na> > >::operator() (
    this=0x1c844b0, args=0x7fffefcc1320, kw=0x0)
    at /usr/include/boost/python/object/py_function.hpp:38
#38 0x00007fffeefbb5cd in boost::python::objects::function::call(_object*, _object*) const () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
#39 0x00007fffeefbb7c8 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
#40 0x00007fffeefc3613 in boost::python::handle_exception_impl(boost::function0<void>) () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
#41 0x00007fffeefb8999 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
#42 0x00000000004b0de3 in PyObject_Call ()
#43 0x00000000004ce140 in PyEval_CallObjectWithKeywords ()
#44 0x0000000000498aed in PyEval_CallFunction ()
#45 0x00007fffef54d936 in boost::python::call<boost::python::api::object, boost::python::tuple, boost::python::dict> (callable=0x1c84520, a0=..., a1=...)
    at /usr/include/boost/python/call.hpp:66
#46 0x00007fffef54d5b9 in boost::python::api::object_operators<boost::python::api::object>::operator()<boost::python::tuple, boost::python::dict> (
    this=0x1c84168, a0=..., a1=...)
    at /usr/include/boost/python/object_call.hpp:19
#47 0x00007fffef54d09f in boost::python::detail::raw_dispatcher<boost::python::api::object>::operator() (this=0x1c84168, args=0x7fffcc03a320, keywords=0x0)
    at /usr/include/boost/python/raw_function.hpp:29
#48 0x00007fffef54cdef in boost::python::objects::full_py_function_impl<boost::python::detail::raw_dispatcher<boost::python::api::object>, boost::mpl::vector1<_object*> >::operator() (this=0x1c84160, args=0x7fffcc03a320, kw=0x0)
    at /usr/include/boost/python/object/py_function.hpp:94
#49 0x00007fffeefbb5cd in boost::python::objects::function::call(_object*, _object*) const () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
#50 0x00007fffeefbb7c8 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
#51 0x00007fffeefc3613 in boost::python::handle_exception_impl(boost::function0<void>) () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
#52 0x00007fffeefb8999 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
#53 0x00000000004b0de3 in PyObject_Call ()
#54 0x00000000004c9b6f in PyEval_EvalFrameEx ()
#55 0x00000000004c994f in PyEval_EvalFrameEx ()
#56 0x00000000004c22e5 in PyEval_EvalCodeEx ()
#57 0x00000000004de7fe in ?? ()
#58 0x00000000004b0de3 in PyObject_Call ()
#59 0x00000000004f49ae in ?? ()
#60 0x00000000004b0de3 in PyObject_Call ()
#61 0x00000000004f4727 in ?? ()
#62 0x00000000004b682c in ?? ()
#63 0x00000000004b0de3 in PyObject_Call ()
#64 0x00000000004c9b6f in PyEval_EvalFrameEx ()
#65 0x00000000004c994f in PyEval_EvalFrameEx ()
#66 0x00000000004c994f in PyEval_EvalFrameEx ()
#67 0x00000000004c22e5 in PyEval_EvalCodeEx ()
#68 0x00000000004c2089 in PyEval_EvalCode ()
#69 0x00000000004f1e6f in ?? ()
#70 0x00000000004ec802 in PyRun_FileExFlags ()
#71 0x00000000004eaf81 in PyRun_SimpleFileExFlags ()
#72 0x000000000049e36a in Py_Main ()
#73 0x00007ffff7811830 in __libc_start_main (main=0x49dcd0 <main>, argc=3, 
    argv=0x7fffffffde08, init=<optimised out>, fini=<optimised out>, 
    rtld_fini=<optimised out>, stack_end=0x7fffffffddf8)
```

The error happens because of the boost::shared_ptr::pn::_pi has a value of 0x131c in my case. This means, the pointer to the counter handling the shared_ptr's reference counting is corrupted (misaligned? since gdb can only report two bytes worth of value). The corrupted value comes from the layerStack->GetIdentifier().pathResolverContext in stack frame #6, at primIndex.cpp::PcpComputePrimIndex. The layer stack's identifier already has the incorrect value, and that's crashing the ArResolverContext's default constructor. There the _context tries to increment the reference counter for the shared pointer, which leads to a crash.

When I build in Release mode, things are fine. For now, I just keep developing in release mode (my dev environment defaults everything to debug). My guess is, it's a strange combination of gcc 5.4 and boost 1.58 that leads to this corruption. I tried tracking down the values further up the stack, but I'm not experienced enough with USD's codebase to figure where things go wrong.

Setting the numThreads to 1 when launching usdview doesn't help either.

Since I was only able to reproduce this with gcc 5.4 (it works fine in our production build env, which is 4.8.3), I don't think we have to worry about this right now, but I'm afraid that it might point to an actual issue, which simply does not happen when building with 4.8.3.

**Comment by sirpalee** [comment]
I forgot to mention, that this issue happened after v0.7.1. Around that release, or shortly after, things were working fine.

**Comment by jtran56** [comment]
Filed as internal issue #139370.

**Comment by sunyab** [comment]
I'm going to close this old bug out. We had not been able to repro this bug on our end and haven't seen any other reports of similar crashes. Given the amount of changes in the 6(!) years since, it doesn't seem feasible to track this any further.
